import ActionFeedback from '@/components/business/ActionFeedback';
import {createBusinessProduct} from '@/app/actions/business';
import {businessMoney,requireBusinessWorkspace} from '@/src/lib/business';
import {supabaseFetch} from '@/src/lib/supabase/server';

export const dynamic='force-dynamic';export const metadata={title:'منتجات التجارة | مَدار'};
export default async function ProductsPage({searchParams}:{searchParams:Promise<{success?:string;error?:string}>}){
 const{workspace}=await requireBusinessWorkspace(),params=await searchParams;
 const products=await supabaseFetch(`/rest/v1/business_products?organization_id=eq.${encodeURIComponent(workspace.id)}&select=*&order=created_at.desc`);
 return <main className="mx-auto max-w-7xl p-5 py-10"><h2 className="text-4xl font-black">المنتجات</h2><p className="mt-2 text-slate-300">كتالوج تجارتك مستقل عن متجر مَدار العام.</p><div className="mt-8 grid gap-8 lg:grid-cols-[380px_1fr]"><section><ActionFeedback {...params}/><form action={createBusinessProduct} className="grid gap-3 rounded-3xl border border-white/10 bg-white/[.04] p-5"><h3 className="text-xl font-black">إضافة منتج</h3><input className="field rounded-xl p-3" name="name" required placeholder="اسم المنتج"/><div className="grid grid-cols-2 gap-3"><input className="field rounded-xl p-3" name="sku" placeholder="SKU اختياري"/><input className="field rounded-xl p-3" name="category" placeholder="التصنيف"/></div><textarea className="field rounded-xl p-3" name="description" rows={3} placeholder="وصف مختصر"/><div className="grid grid-cols-2 gap-3"><input className="field rounded-xl p-3" name="cost" type="number" min="0" step="0.01" defaultValue="0" required placeholder="التكلفة"/><input className="field rounded-xl p-3" name="price" type="number" min="0" step="0.01" required placeholder="سعر البيع"/></div><div className="grid grid-cols-2 gap-3"><input className="field rounded-xl p-3" name="opening_stock" type="number" min="0" step="0.001" defaultValue="0" required placeholder="الرصيد الافتتاحي"/><input className="field rounded-xl p-3" name="low_stock_threshold" type="number" min="0" step="0.001" defaultValue="0" required placeholder="حد التنبيه"/></div><button className="rounded-xl bg-gradient-to-l from-violet-500 to-emerald-400 p-3 font-black">حفظ المنتج</button></form></section><section className="overflow-hidden rounded-3xl border border-white/10"><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-right"><thead className="bg-white/[.06] text-sm text-slate-300"><tr><th className="p-4">المنتج</th><th className="p-4">SKU</th><th className="p-4">السعر</th><th className="p-4">التكلفة</th><th className="p-4">المخزون</th><th className="p-4">الحالة</th></tr></thead><tbody>{products?.length?products.map((p:{id:string;name:string;sku:string|null;price:number;cost:number;stock_quantity:number;low_stock_threshold:number;is_active:boolean})=><tr key={p.id} className="border-t border-white/10"><td className="p-4 font-bold">{p.name}</td><td className="p-4 text-slate-400">{p.sku||'—'}</td><td className="p-4">{businessMoney(p.price,workspace.currency)}</td><td className="p-4">{businessMoney(p.cost,workspace.currency)}</td><td className={`p-4 font-black ${Number(p.stock_quantity)<=Number(p.low_stock_threshold)?'text-amber-200':'text-emerald-200'}`}>{p.stock_quantity}</td><td className="p-4">{p.is_active?'نشط':'مؤرشف'}</td></tr>):<tr><td colSpan={6} className="p-10 text-center text-slate-400">أضف أول منتج لتبدأ تشغيل تجارتك.</td></tr>}</tbody></table></div></section></div></main>;
}
