import ActionFeedback from '@/components/business/ActionFeedback';
import {createBusinessCustomer} from '@/app/actions/business';
import {businessMoney,requireBusinessWorkspace} from '@/src/lib/business';
import {supabaseFetch} from '@/src/lib/supabase/server';

export const dynamic='force-dynamic';export const metadata={title:'العملاء | مَدار'};
const labels:{[key:string]:string}={new:'جديد',active:'نشط',vip:'مميز',inactive:'متوقف'};
export default async function CustomersPage({searchParams}:{searchParams:Promise<{success?:string;error?:string}>}){
 const{workspace}=await requireBusinessWorkspace(),params=await searchParams;
 const customers=await supabaseFetch(`/rest/v1/business_customers?organization_id=eq.${encodeURIComponent(workspace.id)}&select=*&order=created_at.desc`);
 return <main className="mx-auto max-w-7xl p-5 py-10"><h2 className="text-4xl font-black">العملاء CRM</h2><p className="mt-2 text-slate-300">ملف موحد لكل عميل يربط التواصل بالمشتريات والنشاط.</p><div className="mt-8 grid gap-8 lg:grid-cols-[380px_1fr]"><section><ActionFeedback {...params}/><form action={createBusinessCustomer} className="grid gap-3 rounded-3xl border border-white/10 bg-white/[.04] p-5"><h3 className="text-xl font-black">إضافة عميل</h3><input className="field rounded-xl p-3" name="name" required placeholder="اسم العميل"/><div className="grid grid-cols-2 gap-3"><input className="field rounded-xl p-3" name="phone" placeholder="رقم الهاتف"/><input className="field rounded-xl p-3" name="email" type="email" placeholder="البريد"/></div><input className="field rounded-xl p-3" name="address" placeholder="العنوان"/><select className="field rounded-xl p-3" name="status" defaultValue="active"><option value="new">جديد</option><option value="active">نشط</option><option value="vip">مميز</option><option value="inactive">متوقف</option></select><textarea className="field rounded-xl p-3" name="notes" rows={3} placeholder="ملاحظات داخلية"/><button className="rounded-xl bg-gradient-to-l from-violet-500 to-emerald-400 p-3 font-black">حفظ العميل</button></form></section><section className="grid gap-4 md:grid-cols-2">{customers?.length?customers.map((c:{id:string;name:string;phone:string|null;email:string|null;status:string;total_spent:number;last_order_at:string|null;notes:string|null})=><article key={c.id} className="rounded-3xl border border-white/10 bg-white/[.04] p-5"><div className="flex items-start justify-between gap-4"><div><h3 className="text-xl font-black">{c.name}</h3><p className="mt-1 text-sm text-[#70E4D4]">{labels[c.status]||c.status}</p></div><strong>{businessMoney(c.total_spent,workspace.currency)}</strong></div><p className="mt-4 text-sm text-slate-300">{c.phone||'لا يوجد هاتف'}{c.email?` · ${c.email}`:''}</p>{c.last_order_at&&<p className="mt-2 text-xs text-slate-400">آخر شراء: {new Date(c.last_order_at).toLocaleString('ar-YE')}</p>}{c.notes&&<p className="mt-3 border-t border-white/10 pt-3 text-sm text-slate-400">{c.notes}</p>}</article>):<p className="md:col-span-2 rounded-3xl border border-white/10 p-10 text-center text-slate-400">لا يوجد عملاء بعد.</p>}</section></div></main>;
}
