'use client';

import {useActionState,useEffect,useState} from 'react';
import {addCourse,addEvent,addGoal,addNote,addSchedule,addStudySession,addTask,uploadStudentPdf,type StudentState} from '@/app/actions/student';
import {Button,Field,Input,Notice,Select,Textarea} from '@/components/ui/Enterprise';

type Course={id:string;name:string};
const initial:StudentState={};
function Message({state}:{state:StudentState}){return <>{state.error&&<Notice title="تعذر الحفظ" variant="danger">{state.error}</Notice>}{state.success&&<Notice title="تم الحفظ" variant="success">{state.success}</Notice>}</>}
function Submit({pending,label}:{pending:boolean;label:string}){return <Button disabled={pending}>{pending?'جارٍ الحفظ…':label}</Button>}
function CourseSelect({courses}:{courses:Course[]}){return <Field label="المقرر"><Select name="course_id"><option value="">دون ربط بمقرر</option>{courses.map(course=><option key={course.id} value={course.id}>{course.name}</option>)}</Select></Field>}

export function CourseForm({org}:{org:string}){const[state,action,pending]=useActionState(addCourse,initial);return <form action={action} className="grid gap-3"><input type="hidden" name="organization_id" value={org}/><div className="grid gap-3 sm:grid-cols-2"><Field label="اسم المقرر"><Input name="name" required/></Field><Field label="رمز المقرر"><Input name="code"/></Field></div><div className="grid grid-cols-2 gap-3"><Field label="الساعات"><Input name="credits" type="number" min="0.5" max="30" step="0.5" required/></Field><Field label="الدرجة الحالية"><Input name="grade" type="number" min="0" max="100" step="0.01" required/></Field></div><div className="grid gap-3 sm:grid-cols-2"><Field label="الدرجة المستهدفة"><Input name="target_grade" type="number" min="0" max="100"/></Field><Field label="اسم المدرس"><Input name="instructor"/></Field></div><div className="grid grid-cols-[1fr_auto] gap-3"><Field label="الفصل الدراسي"><Input name="semester"/></Field><Field label="لون المقرر"><Input name="color" type="color" defaultValue="#6C3BFF" className="h-12 w-16 p-1" aria-label="لون المقرر"/></Field></div><Submit pending={pending} label="إضافة المقرر"/><Message state={state}/></form>}

export function TaskForm({org,courses}:{org:string;courses:Course[]}){const[state,action,pending]=useActionState(addTask,initial);return <form action={action} className="grid gap-3"><input type="hidden" name="organization_id" value={org}/><Field label="عنوان المهمة"><Input name="title" required/></Field><Field label="تفاصيل مختصرة"><Textarea name="description" rows={2}/></Field><CourseSelect courses={courses}/><div className="grid gap-3 sm:grid-cols-2"><Field label="الأولوية"><Select name="priority"><option value="LOW">منخفضة</option><option value="MEDIUM">متوسطة</option><option value="HIGH">عالية</option></Select></Field><Field label="موعد التسليم"><Input name="due_at" type="datetime-local"/></Field></div><Field label="موعد التذكير"><Input name="reminder_at" type="datetime-local"/></Field><Submit pending={pending} label="إضافة المهمة"/><Message state={state}/></form>}

export function NoteForm({org}:{org:string}){const[state,action,pending]=useActionState(addNote,initial);return <form action={action} className="grid gap-3"><input type="hidden" name="organization_id" value={org}/><Field label="عنوان الملاحظة"><Input name="title" required/></Field><Field label="المحتوى"><Textarea name="content" required maxLength={5000} rows={5} placeholder="اكتب أفكارك أو ملخص المحاضرة…"/></Field><Field label="الوسوم" help="افصل بين الوسوم بفاصلة"><Input name="tags"/></Field><div className="grid grid-cols-2 gap-3"><Field label="اللون"><Select name="color"><option value="amber">ذهبي</option><option value="violet">بنفسجي</option><option value="emerald">أخضر</option><option value="blue">أزرق</option></Select></Field><label className="flex items-center gap-2 self-end rounded-xl border border-white/10 p-3"><input name="is_pinned" type="checkbox" className="accent-violet-500"/> تثبيت الملاحظة</label></div><Submit pending={pending} label="حفظ الملاحظة"/><Message state={state}/></form>}

export function ScheduleForm({org,courses}:{org:string;courses:Course[]}){const[state,action,pending]=useActionState(addSchedule,initial);return <form action={action} className="grid gap-3"><input type="hidden" name="organization_id" value={org}/><Field label="عنوان الموعد"><Input name="title" required placeholder="المحاضرة أو جلسة المذاكرة"/></Field><CourseSelect courses={courses}/><div className="grid grid-cols-2 gap-3"><Field label="اليوم"><Select name="weekday">{['الأحد','الاثنين','الثلاثاء','الأربعاء','الخميس','الجمعة','السبت'].map((day,index)=><option key={day} value={index}>{day}</option>)}</Select></Field><Field label="النوع"><Select name="kind"><option value="LECTURE">محاضرة</option><option value="LAB">تطبيقي</option><option value="STUDY">مذاكرة</option><option value="OTHER">أخرى</option></Select></Field></div><div className="grid grid-cols-2 gap-3"><Field label="وقت البداية"><Input name="starts_at" type="time" required/></Field><Field label="وقت النهاية"><Input name="ends_at" type="time" required/></Field></div><Field label="القاعة أو المكان"><Input name="location"/></Field><Submit pending={pending} label="إضافة إلى الجدول"/><Message state={state}/></form>}

export function EventForm({org,courses}:{org:string;courses:Course[]}){const[state,action,pending]=useActionState(addEvent,initial);return <form action={action} className="grid gap-3"><input type="hidden" name="organization_id" value={org}/><Field label="عنوان الموعد"><Input name="title" required placeholder="اختبار أو تسليم أو عرض"/></Field><CourseSelect courses={courses}/><div className="grid gap-3 sm:grid-cols-2"><Field label="نوع الموعد"><Select name="kind"><option value="EXAM">اختبار</option><option value="ASSIGNMENT">واجب</option><option value="PRESENTATION">عرض</option><option value="DEADLINE">موعد نهائي</option><option value="OTHER">أخرى</option></Select></Field><Field label="التاريخ والوقت"><Input name="starts_at" required type="datetime-local"/></Field></div><Field label="موعد التذكير"><Input name="reminder_at" type="datetime-local"/></Field><Field label="المكان"><Input name="location"/></Field><Field label="ملاحظات الاستعداد"><Textarea name="notes" rows={2}/></Field><Submit pending={pending} label="حفظ الموعد"/><Message state={state}/></form>}

export function StudySessionForm({org,courses}:{org:string;courses:Course[]}){const[state,action,pending]=useActionState(addStudySession,initial);return <form action={action} className="grid gap-3"><input type="hidden" name="organization_id" value={org}/><Field label="عنوان جلسة المذاكرة"><Input name="title" required/></Field><CourseSelect courses={courses}/><div className="grid grid-cols-3 gap-3"><Field label="الدقائق"><Input name="minutes" required type="number" min="1" max="1440"/></Field><Field label="التاريخ"><Input name="studied_on" required type="date" defaultValue={new Date().toISOString().slice(0,10)}/></Field><Field label="التركيز"><Select name="focus_score"><option value="">غير محدد</option>{[1,2,3,4,5].map(value=><option key={value}>{value}</option>)}</Select></Field></div><Field label="ما الذي أنجزته؟"><Textarea name="notes" rows={2}/></Field><Submit pending={pending} label="تسجيل الجلسة"/><Message state={state}/></form>}

export function GoalForm({org}:{org:string}){const[state,action,pending]=useActionState(addGoal,initial);return <form action={action} className="grid gap-3"><input type="hidden" name="organization_id" value={org}/><Field label="الهدف الدراسي"><Input name="title" required placeholder="مثال: مذاكرة إدارة العمليات"/></Field><div className="grid grid-cols-3 gap-3"><Field label="القيمة المستهدفة"><Input name="target_value" required type="number" min="1"/></Field><Field label="الوحدة"><Input name="unit" required defaultValue="ساعة"/></Field><Field label="الموعد النهائي"><Input name="deadline" type="date"/></Field></div><Submit pending={pending} label="إضافة الهدف"/><Message state={state}/></form>}

export function PdfForm({org}:{org:string}){const[state,action,pending]=useActionState(uploadStudentPdf,initial);return <form action={action} encType="multipart/form-data" className="grid gap-3"><input type="hidden" name="organization_id" value={org}/><Field label="عنوان الملزمة أو المرجع"><Input name="title" required/></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="المادة"><Input name="subject"/></Field><Field label="التصنيف"><Select name="category"><option value="SUMMARY">ملخص</option><option value="HANDOUT">ملزمة</option><option value="BOOK">كتاب</option><option value="RESEARCH">بحث</option><option value="REFERENCE">مرجع</option></Select></Field></div><Field label="وصف مختصر"><Textarea name="description" rows={2}/></Field><Field label="ملف المستند المحمول" help="يُحفظ الملف داخل مكتبتك الخاصة"><Input name="file" type="file" accept="application/pdf" required/></Field><Submit pending={pending} label="إضافة إلى الرف"/><Message state={state}/></form>}

export function StudyTimer(){const[seconds,setSeconds]=useState(25*60),[running,setRunning]=useState(false);useEffect(()=>{if(!running)return;const id=window.setInterval(()=>setSeconds(value=>{if(value<=1){setRunning(false);return 0}return value-1}),1000);return()=>window.clearInterval(id)},[running]);return <div className="text-center"><p className="text-5xl font-black text-emerald-300" aria-live="polite">{String(Math.floor(seconds/60)).padStart(2,'0')}:{String(seconds%60).padStart(2,'0')}</p><div className="mt-4 flex flex-col justify-center gap-2 sm:flex-row"><Button type="button" onClick={()=>setRunning(value=>!value)}>{running?'إيقاف':'ابدأ التركيز'}</Button><Button type="button" variant="secondary" onClick={()=>{setRunning(false);setSeconds(25*60)}}>إعادة الضبط</Button></div></div>}
