/* eslint-disable @typescript-eslint/no-explicit-any */
import Link from 'next/link';
import {requireUser} from '@/src/lib/auth';
import {supabaseFetch} from '@/src/lib/supabase/server';
import {deleteDocument,deleteStudentItem,ensureStudentWorkspace,toggleDocumentFavorite,toggleTask} from '@/app/actions/student';
import {CourseForm,EventForm,GoalForm,NoteForm,PdfForm,ScheduleForm,StudySessionForm,StudyTimer,TaskForm} from './forms';
import StudentAssistant from './assistant';
import {Badge,Button,Card,EmptyState} from '@/components/ui/Enterprise';
import {Icon} from '@/components/ui/Icons';

export const dynamic='force-dynamic';
const days=['الأحد','الاثنين','الثلاثاء','الأربعاء','الخميس','الجمعة','السبت'];
const priority:{[key:string]:string}={HIGH:'عالية',MEDIUM:'متوسطة',LOW:'منخفضة'};
const eventKinds:{[key:string]:string}={EXAM:'اختبار',ASSIGNMENT:'واجب',PRESENTATION:'عرض',DEADLINE:'موعد نهائي',OTHER:'أخرى'};
const category:{[key:string]:string}={SUMMARY:'ملخص',HANDOUT:'ملزمة',BOOK:'كتاب',RESEARCH:'بحث',REFERENCE:'مرجع'};
const assistantModes:{[key:string]:string}={PLAN:'خطة مذاكرة',SUMMARY:'تلخيص',QUIZ:'أسئلة مراجعة',EXPLAIN:'شرح'};

export default async function Page({searchParams}:{searchParams:Promise<{q?:string;sort?:string;subject?:string}>}){
 const user=await requireUser(),params=await searchParams;
 const members=await supabaseFetch(`/rest/v1/organization_members?user_id=eq.${user.id}&select=organization_id,organizations(id,name,type,status)&order=created_at.asc`);
 const workspace=members?.map((item:any)=>item.organizations).find((item:any)=>item?.type==='STUDENT'&&item.status==='active');
 if(!workspace)return <CreateStudentSpace/>;
 const org=workspace.id;
 await supabaseFetch('/rest/v1/rpc/sync_student_reminders',{method:'POST',body:JSON.stringify({target_organization:org})}).catch(()=>null);
 const[courses,tasks,notes,schedule,allDocuments,events,sessions,goals,aiHistory]=await Promise.all([
  supabaseFetch(`/rest/v1/student_courses?organization_id=eq.${org}&select=*&order=created_at.desc`),
  supabaseFetch(`/rest/v1/student_tasks?organization_id=eq.${org}&select=*,student_courses(name,color)&order=is_done.asc,due_at.asc.nullslast`),
  supabaseFetch(`/rest/v1/student_notes?organization_id=eq.${org}&select=*&order=is_pinned.desc,updated_at.desc`),
  supabaseFetch(`/rest/v1/student_schedule?organization_id=eq.${org}&select=*,student_courses(name,color)&order=weekday.asc,starts_at.asc`),
  supabaseFetch(`/rest/v1/student_documents?organization_id=eq.${org}&select=*&order=created_at.desc`),
  supabaseFetch(`/rest/v1/student_events?organization_id=eq.${org}&select=*,student_courses(name,color)&order=starts_at.asc`),
  supabaseFetch(`/rest/v1/student_study_sessions?organization_id=eq.${org}&select=*,student_courses(name,color)&order=studied_on.desc,created_at.desc&limit=30`),
  supabaseFetch(`/rest/v1/student_goals?organization_id=eq.${org}&select=*&order=is_done.asc,deadline.asc.nullslast`),
  supabaseFetch(`/rest/v1/student_ai_history?organization_id=eq.${org}&select=id,mode,prompt_excerpt,response,created_at&order=created_at.desc&limit=5`)
 ]);
 const credits=courses.reduce((total:number,item:any)=>total+Number(item.credits),0),average=credits?courses.reduce((total:number,item:any)=>total+Number(item.grade)*Number(item.credits),0)/credits:null;
 const weekMinutes=sessions.filter((item:any)=>+new Date()-new Date(item.studied_on).getTime()<7*86400000).reduce((total:number,item:any)=>total+item.minutes,0);
 const upcoming=events.filter((item:any)=>new Date(item.starts_at)>=new Date()).slice(0,5);
 const q=String(params.q||'').trim().toLowerCase(),subject=String(params.subject||''),sort=params.sort||'date-desc';
 let documents=allDocuments.filter((item:any)=>(!q||`${item.title} ${item.subject||''} ${item.original_filename}`.toLowerCase().includes(q))&&(!subject||item.subject===subject));
 documents=[...documents].sort((a:any,b:any)=>sort==='name'?a.title.localeCompare(b.title,'ar'):sort==='size-desc'?b.file_size-a.file_size:sort==='size-asc'?a.file_size-b.file_size:sort==='date-asc'?+new Date(a.created_at)-+new Date(b.created_at):+new Date(b.created_at)-+new Date(a.created_at));
 const subjects=[...new Set(allDocuments.map((item:any)=>item.subject).filter(Boolean))] as string[];
 return <main className="md-container md-page">
  <header className="relative overflow-hidden rounded-[2rem] border border-white/10 bg-[#101625] p-7 shadow-2xl sm:p-10"><div className="absolute inset-0 bg-[radial-gradient(circle_at_85%_15%,rgba(124,77,255,.35),transparent_38%),radial-gradient(circle_at_15%_85%,rgba(50,214,189,.22),transparent_36%)]"/><div className="relative"><Badge variant="success">مساهمة مَدار المجتمعية · مجانية لكل حساب</Badge><h1 className="mt-5 text-3xl font-black sm:text-5xl">مساحة الطالب · {workspace.name}</h1><p className="mt-4 max-w-3xl leading-8 text-slate-300">مركز جامعي خاص يجمع معدلك ومقرراتك ومكتبتك ومواعيدك وتركيزك وأهدافك، مع أوربي مساعد مَدار الذكي.</p><nav className="md-tabs mt-7 border-white/10" aria-label="أقسام مساحة الطالب">{[['overview','نظرة عامة'],['courses','المقررات'],['tasks','المهام'],['library','المكتبة'],['calendar','الجدول والمواعيد'],['notes','الملاحظات'],['focus','التركيز والأهداف'],['ai','أوربي']].map(item=><a key={item[0]} href={`#${item[0]}`} className="md-tab">{item[1]}</a>)}</nav></div></header>
  <section id="overview" className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><Stat label="المعدل الموزون" value={average===null?'—':`${average.toFixed(2)}%`} accent/><Stat label="المقررات" value={courses.length}/><Stat label="المهام المتبقية" value={tasks.filter((item:any)=>!item.is_done).length}/><Stat label="مذاكرة آخر سبعة أيام" value={`${Math.round(weekMinutes/60*10)/10} ساعة`}/><Stat label="المراجع" value={allDocuments.length}/></section>
  {upcoming.length>0&&<section className="md-notice md-notice-warning mt-6 block"><h2 className="text-xl font-black text-amber-200">القادم في تقويمك</h2><div className="mt-3 grid gap-3 md:grid-cols-2">{upcoming.map((item:any)=><div key={item.id} className="rounded-xl bg-white/5 p-3"><b>{eventKinds[item.kind]} · {item.title}</b><p className="mt-1 text-sm text-slate-300">{formatDate(item.starts_at)} {item.student_courses?.name&&`· ${item.student_courses.name}`}</p></div>)}</div></section>}
  <div className="mt-6 grid gap-6 lg:grid-cols-2">
   <Panel id="courses" title="المقررات وحساب المعدل" description="معدل موزون بالساعات مع الدرجة الحالية والمستهدفة."><CourseForm org={org}/><List empty="لم تضف مقررات بعد.">{courses.map((item:any)=><Item key={item.id} color={item.color}><div><b>{item.name}</b><p className="text-sm text-slate-400">{item.code||'دون رمز'} · {item.credits} ساعة {item.instructor&&`· ${item.instructor}`}</p></div><div className="text-left"><b>{item.grade}%</b>{item.target_grade&&<p className="text-xs text-emerald-300">الهدف {item.target_grade}%</p>}</div><Delete org={org} id={item.id} table="student_courses"/></Item>)}</List></Panel>
   <Panel id="tasks" title="المهام والتذكيرات" description="أولوية وموعد تسليم وتنبيه يظهر في مركز إشعاراتك."><TaskForm org={org} courses={courses}/><List empty="لا توجد مهام معلقة.">{tasks.map((item:any)=><form action={toggleTask} key={item.id} className="md-card flex items-start gap-3 p-3"><input type="hidden" name="organization_id" value={org}/><input type="hidden" name="id" value={item.id}/><input type="hidden" name="is_done" value={String(item.is_done)}/><button aria-label="تغيير حالة المهمة" className={`mt-1 grid h-7 w-7 shrink-0 place-items-center rounded-full border ${item.is_done?'bg-emerald-400 text-black':'border-white/30'}`}>{item.is_done?'✓':''}</button><div className="min-w-0 flex-1"><b className={item.is_done?'text-slate-500 line-through':''}>{item.title}</b><p className="text-xs text-slate-400">{priority[item.priority]} {item.student_courses?.name&&`· ${item.student_courses.name}`} {item.due_at&&`· ${formatDate(item.due_at)}`}</p></div></form>)}</List></Panel>
  </div>
  <Panel id="library" title="مكتبة الطالب" description="ملازم وملخصات وكتب بصيغة المستند المحمول، مرتبة على رفوف رقمية."><PdfForm org={org}/><form className="mt-6 grid gap-3 rounded-2xl border border-white/10 bg-white/[.025] p-4 sm:grid-cols-4"><input name="q" defaultValue={params.q} className="field" placeholder="ابحث بالاسم أو المادة"/><select name="subject" defaultValue={subject} className="field"><option value="">كل المواد</option>{subjects.map(value=><option key={value}>{value}</option>)}</select><select name="sort" defaultValue={sort} className="field"><option value="date-desc">الأحدث</option><option value="date-asc">الأقدم</option><option value="name">حسب الاسم</option><option value="size-desc">الحجم: الأكبر</option><option value="size-asc">الحجم: الأصغر</option></select><button className="md-button md-button-primary">تطبيق التصفية</button></form><div className="mt-7 border-b-8 border-amber-950/70 pb-3"><div className="grid grid-cols-2 gap-4 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6">{documents.map((item:any)=><article key={item.id} className="group relative flex aspect-[3/4] flex-col justify-between rounded-r-md rounded-l-2xl border-r-8 border-amber-300 bg-gradient-to-br from-violet-700 to-slate-950 p-4 shadow-xl transition hover:-translate-y-2"><span className="text-xs text-white/60">{category[item.category]} · {item.subject||'عام'}</span><strong className="line-clamp-4">{item.title}</strong><div><span className="block text-xs text-white/60">{formatBytes(item.file_size)} · {new Date(item.created_at).toLocaleDateString('ar-YE')}</span><a href={`/student/documents/${item.id}`} target="_blank" className="mt-2 inline-block text-sm font-bold text-emerald-300">فتح المستند</a></div><div className="absolute left-2 top-2 flex gap-1"><form action={toggleDocumentFavorite}><input type="hidden" name="organization_id" value={org}/><input type="hidden" name="id" value={item.id}/><input type="hidden" name="is_favorite" value={String(item.is_favorite)}/><button aria-label="المفضلة" className="rounded-full bg-black/40 p-2">{item.is_favorite?'★':'☆'}</button></form><form action={deleteDocument}><input type="hidden" name="organization_id" value={org}/><input type="hidden" name="id" value={item.id}/><button aria-label="حذف الملف" className="rounded-full bg-black/40 p-2 text-red-200">×</button></form></div></article>)}</div>{documents.length===0&&<EmptyState title="لا توجد ملفات مطابقة" description="غيّر التصفية أو أضف مستندًا جديدًا إلى مكتبتك."/>}</div></Panel>
  <div className="mt-6 grid gap-6 lg:grid-cols-2"><Panel id="calendar" title="الجدول الأسبوعي"><ScheduleForm org={org} courses={courses}/><List empty="الجدول فارغ.">{schedule.map((item:any)=><Item key={item.id} color={item.student_courses?.color}><div><b>{days[item.weekday]} · {String(item.starts_at).slice(0,5)}–{String(item.ends_at).slice(0,5)}</b><p className="text-sm text-slate-400">{item.title}{item.location?` · ${item.location}`:''}</p></div><Delete org={org} id={item.id} table="student_schedule"/></Item>)}</List><h3 className="mb-3 mt-8 text-xl font-black">الاختبارات والمواعيد النهائية</h3><EventForm org={org} courses={courses}/><List empty="لا توجد مواعيد.">{events.map((item:any)=><Item key={item.id} color={item.student_courses?.color}><div><b>{eventKinds[item.kind]} · {item.title}</b><p className="text-sm text-slate-400">{formatDate(item.starts_at)} {item.location&&`· ${item.location}`}</p></div><Delete org={org} id={item.id} table="student_events"/></Item>)}</List></Panel>
  <Panel id="notes" title="دفتر الملاحظات"><NoteForm org={org}/><div className="mt-5 grid gap-3 sm:grid-cols-2">{notes.map((item:any)=><article key={item.id} className={`${noteColor(item.color)} relative rounded-2xl p-4 text-slate-950 shadow`}><div className="flex items-start justify-between"><h3 className="font-black">{item.is_pinned&&'📌 '}{item.title}</h3><Delete org={org} id={item.id} table="student_notes" dark/></div><p className="mt-2 whitespace-pre-wrap text-sm leading-6">{item.content}</p>{item.tags?.length>0&&<div className="mt-3 flex flex-wrap gap-1">{item.tags.map((tag:string)=><span key={tag} className="rounded-full bg-black/10 px-2 py-1 text-xs">#{tag}</span>)}</div>}</article>)}</div></Panel></div>
  <div className="mt-6 grid gap-6 lg:grid-cols-2"><Panel id="focus" title="التركيز وسجل المذاكرة"><StudyTimer/><div className="mt-7"><StudySessionForm org={org} courses={courses}/></div><List empty="لم تسجل جلسات بعد.">{sessions.map((item:any)=><Item key={item.id} color={item.student_courses?.color}><div><b>{item.title}</b><p className="text-sm text-slate-400">{item.minutes} دقيقة · تركيز {item.focus_score||'—'}/5 · {item.studied_on}</p></div><Delete org={org} id={item.id} table="student_study_sessions"/></Item>)}</List></Panel><Panel title="الأهداف الدراسية"><GoalForm org={org}/><List empty="أضف هدفك الدراسي الأول.">{goals.map((item:any)=>{const percent=Math.min(100,Math.round(item.current_value/item.target_value*100));return <Item key={item.id}><div className="w-full"><div className="flex justify-between"><b>{item.title}</b><span>{item.current_value}/{item.target_value} {item.unit}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full bg-emerald-400" style={{width:`${percent}%`}}/></div></div><Delete org={org} id={item.id} table="student_goals"/></Item>})}</List></Panel></div>
  <Panel id="ai" title="أوربي، مساعد مَدار الذكي" description="خطط مذاكرة وتلخيص وشرح وأسئلة مراجعة بالعربية، مع حفظ آخر النتائج في مساحتك."><StudentAssistant organizationId={org}/>{aiHistory.length>0&&<details className="mt-6 rounded-2xl border border-white/10 bg-white/[.025] p-4"><summary className="cursor-pointer font-bold">آخر نتائج أوربي</summary><div className="mt-4 grid gap-3">{aiHistory.map((item:any)=><article key={item.id} className="md-card p-4"><p className="text-xs text-emerald-300">{assistantModes[item.mode]||'مساعدة دراسية'} · {formatDate(item.created_at)}</p><b className="mt-1 block">{item.prompt_excerpt}</b><p className="mt-2 line-clamp-5 whitespace-pre-wrap text-sm text-slate-300">{item.response}</p></article>)}</div></details>}</Panel>
 </main>;
}

function CreateStudentSpace(){return <main className="md-container md-page"><Card className="mx-auto max-w-2xl border-violet-300/20 bg-gradient-to-br from-violet-700/20 to-emerald-500/10 p-8 text-center"><span className="mx-auto grid h-16 w-16 place-items-center rounded-2xl bg-violet-300/10 text-4xl">🎓</span><h1 className="mt-5 text-4xl font-black">مساحة الطالب المجانية</h1><p className="mt-4 leading-8 text-slate-300">متاحة لكل حساب في مَدار، بما في ذلك حساب المالك وأصحاب المساحات التجارية. تنشأ كمساحة مستقلة ولا تؤثر على نشاطك الحالي.</p><form action={ensureStudentWorkspace}><Button className="mt-7" size="lg">إنشاء مساحتي الجامعية</Button></form><Link href="/account" className="mt-5 block text-sm text-slate-400">العودة إلى حسابي</Link></Card></main>}
function Panel({id,title,description,children}:{id?:string;title:string;description?:string;children:React.ReactNode}){return <section id={id} className="md-panel mt-6 scroll-mt-24"><h2 className="text-2xl font-black">{title}</h2>{description&&<p className="mb-5 mt-2 leading-7 text-slate-400">{description}</p>}{!description&&<div className="h-5"/>}{children}</section>}
function Stat({label,value,accent}:{label:string;value:string|number;accent?:boolean}){return <div className="md-stat"><span className="md-stat-label">{label}</span><p className={`md-stat-value ${accent?'text-emerald-300':''}`}>{value}</p></div>}
function List({empty,children}:{empty:string;children:React.ReactNode[]}){return <div className="mt-5 space-y-2">{children.length?children:<p className="rounded-xl border border-dashed border-white/10 bg-white/[.025] p-4 text-center text-sm text-slate-500">{empty}</p>}</div>}
function Item({color,children}:{color?:string;children:React.ReactNode}){return <div className="md-card flex items-center gap-3 p-3" style={{borderInlineStart:`4px solid ${color||'#334155'}`}}>{children}</div>}
function Delete({org,id,table,dark}:{org:string;id:string;table:string;dark?:boolean}){return <form action={deleteStudentItem} className="mr-auto"><input type="hidden" name="organization_id" value={org}/><input type="hidden" name="id" value={id}/><input type="hidden" name="table" value={table}/><button aria-label="حذف" className={`md-button md-button-ghost md-button-sm ${dark?'text-red-800':'text-red-300'}`}>حذف</button></form>}
function formatBytes(n:number){if(n<1024*1024)return `${Math.ceil(n/1024)} كيلوبايت`;return `${(n/1024/1024).toFixed(1)} ميجابايت`}
function formatDate(value:string){return new Intl.DateTimeFormat('ar-YE',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Aden'}).format(new Date(value))}
function noteColor(value:string){return value==='violet'?'bg-violet-200':value==='emerald'?'bg-emerald-200':value==='blue'?'bg-blue-200':'bg-amber-200'}
