'use server';
import { cookies } from 'next/headers'; import { redirect } from 'next/navigation'; import { supabaseConfig, siteUrl } from '@/src/lib/env'; import { safeReturnTo } from '@/src/lib/auth';
async function auth(path:string, body:unknown){const {url,key}=supabaseConfig();const r=await fetch(`${url}/auth/v1/${path}`,{method:'POST',headers:{apikey:key,'Content-Type':'application/json'},body:JSON.stringify(body),cache:'no-store'});const json=await r.json();if(!r.ok)throw new Error(json.msg||json.error_description||'تعذر إتمام العملية.');return json;}
async function setSession(session:{access_token:string;refresh_token:string;expires_in:number}){const jar=await cookies();const options={httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax' as const,path:'/',maxAge:session.expires_in};jar.set('madar-access-token',session.access_token,options);jar.set('madar-refresh-token',session.refresh_token,options);}
export async function login(form:FormData){try{const email=String(form.get('email')||'').trim().toLowerCase(),password=String(form.get('password')||'');if(!email||!password)throw new Error('أدخل البريد وكلمة المرور.');const result=await auth('token?grant_type=password',{email,password});await setSession(result);redirect(safeReturnTo(String(form.get('next')||''),'/account'));}catch(e){return {error:e instanceof Error?e.message:'تعذر تسجيل الدخول.'};}}
export async function register(form:FormData){try{const full_name=String(form.get('full_name')||'').trim(),email=String(form.get('email')||'').trim().toLowerCase(),password=String(form.get('password')||''),confirm=String(form.get('confirm')||'');if(full_name.length<2)throw new Error('الاسم الكامل يجب أن يكون حرفين على الأقل.');if(!/^\S+@\S+\.\S+$/.test(email))throw new Error('البريد الإلكتروني غير صالح.');if(password.length<8)throw new Error('كلمة المرور يجب أن تكون 8 أحرف على الأقل.');if(password!==confirm)throw new Error('تأكيد كلمة المرور غير مطابق.');if(form.get('terms')!=='on')throw new Error('يلزم قبول الشروط.');await auth('signup',{email,password,data:{full_name},options:{emailRedirectTo:`${siteUrl()}/auth/callback`}});return {success:'أرسلنا رسالة تأكيد إلى بريدك الإلكتروني.'};}catch(e){return {error:e instanceof Error?e.message:'تعذر إنشاء الحساب.'};}}
export async function forgotPassword(form:FormData){try{const email=String(form.get('email')||'').trim();if(/^\S+@\S+\.\S+$/.test(email))await auth('recover',{email,options:{redirectTo:`${siteUrl()}/reset-password`}});return {success:'إذا كان البريد مسجلاً، ستصلك رسالة استعادة.'};}catch{return {success:'إذا كان البريد مسجلاً، ستصلك رسالة استعادة.'};}}
export async function logout(){const jar=await cookies();jar.delete('madar-access-token');jar.delete('madar-refresh-token');redirect('/');}
export async function updateProfile(form:FormData){const { currentUser,supabaseFetch }=await import('@/src/lib/supabase/server');const user=await currentUser();if(!user)return {error:'يجب تسجيل الدخول.'};try{await supabaseFetch(`/rest/v1/profiles?id=eq.${user.id}`,{method:'PATCH',body:JSON.stringify({full_name:String(form.get('full_name')||'').trim(),phone:String(form.get('phone')||'').trim()||null})});return {success:'تم حفظ الملف الشخصي.'};}catch{return {error:'تعذر حفظ الملف الشخصي.'};}}
