'use server';
import { cookies } from 'next/headers';import { redirect } from 'next/navigation';import {revalidatePath}from'next/cache';import { supabaseConfig,siteUrl } from '@/src/lib/env';import { safeReturnTo } from '@/src/lib/auth';import { email,password } from '@/src/lib/validation';import{validateMagicBytes}from'@/src/lib/file-signatures.mjs';
async function auth(path:string,body:unknown){const {url,key}=supabaseConfig();const r=await fetch(`${url}/auth/v1/${path}`,{method:'POST',headers:{apikey:key,'Content-Type':'application/json'},body:JSON.stringify(body),cache:'no-store'});const json=await r.json();if(!r.ok)throw new Error(json.msg||json.error_description||'تعذر إتمام العملية.');return json;}
const cookieOptions=(maxAge:number)=>({httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax' as const,path:'/',maxAge});
async function setSession(session:{access_token:string;refresh_token:string;expires_in:number}){const jar=await cookies();jar.set('madar-access-token',session.access_token,cookieOptions(session.expires_in));jar.set('madar-refresh-token',session.refresh_token,cookieOptions(60*60*24*30));}
export async function login(_previous:unknown,form:FormData){let destination='/account';try{const result=await auth('token?grant_type=password',{email:email(String(form.get('email')||'')),password:password(String(form.get('password')||''))});await setSession(result);destination=safeReturnTo(String(form.get('next')||''),'/account');}catch(e){return {error:e instanceof Error?e.message:'تعذر تسجيل الدخول.'};}redirect(destination);}
export async function register(_previous:unknown,form:FormData){try{const full_name=String(form.get('full_name')||'').trim();if(full_name.length<2)throw new Error('الاسم الكامل يجب أن يكون حرفين على الأقل.');const userEmail=email(String(form.get('email')||''));const userPassword=password(String(form.get('password')||''),String(form.get('confirm')||''));if(form.get('terms')!=='on')throw new Error('يلزم قبول الشروط.');const redirectTo=encodeURIComponent(`${siteUrl()}/auth/callback`);await auth(`signup?redirect_to=${redirectTo}`,{email:userEmail,password:userPassword,data:{full_name}});}catch(e){return {error:e instanceof Error?e.message:'تعذر إنشاء الحساب.'};}redirect('/login?registered=1');}
export async function forgotPassword(_previous:unknown,form:FormData){try{const userEmail=String(form.get('email')||'').trim();if(/^\S+@\S+\.\S+$/.test(userEmail)){const redirectTo=encodeURIComponent(`${siteUrl()}/auth/callback?next=/reset-password`);await auth(`recover?redirect_to=${redirectTo}`,{email:userEmail});}return {success:'إذا كان البريد مسجلاً، ستصلك رسالة استعادة.'};}catch{return {success:'إذا كان البريد مسجلاً، ستصلك رسالة استعادة.'};}}
export async function resetPassword(_previous:unknown,form:FormData){try{const value=password(String(form.get('password')||''),String(form.get('confirm')||''));const {currentUser,supabaseFetch}=await import('@/src/lib/supabase/server');if(!await currentUser())throw new Error('انتهت جلسة الاستعادة؛ اطلب رابطاً جديداً.');await supabaseFetch('/auth/v1/user',{method:'PUT',body:JSON.stringify({password:value})});return {success:'تم تغيير كلمة المرور بنجاح. يمكنك تسجيل الدخول بها الآن.'};}catch(error){return {error:error instanceof Error?error.message:'تعذر تغيير كلمة المرور.'};}}
export async function logout(){const jar=await cookies();const token=jar.get('madar-access-token')?.value;if(token){const {url,key}=supabaseConfig();await fetch(`${url}/auth/v1/logout`,{method:'POST',headers:{apikey:key,Authorization:`Bearer ${token}`},cache:'no-store'}).catch(()=>undefined);}jar.set('madar-access-token','',{...cookieOptions(0),maxAge:0});jar.set('madar-refresh-token','',{...cookieOptions(0),maxAge:0});redirect('/');}
export async function updateProfile(_previous:unknown,form:FormData){const {currentUser,supabaseFetch,serverToken}=await import('@/src/lib/supabase/server');const user=await currentUser();if(!user)return {error:'يجب تسجيل الدخول.'};try{const full_name=String(form.get('full_name')||'').trim();if(full_name.length<2)throw new Error('الاسم الكامل يجب أن يكون حرفين على الأقل.');const values:{full_name:string;phone:string|null;avatar_url?:string}={full_name,phone:String(form.get('phone')||'').trim()||null};const avatar=form.get('avatar');if(avatar instanceof File&&avatar.size){const allowed:Record<string,string>={'image/jpeg':'jpg','image/png':'png','image/webp':'webp'};const ext=allowed[avatar.type];if(!ext||avatar.size>5*1024*1024)throw new Error('الصورة يجب أن تكون JPEG أو PNG أو WebP وبحجم لا يتجاوز 5 ميجابايت.');if(!await validateMagicBytes(avatar))throw new Error('محتوى الصورة لا يطابق نوع الملف.');const {url,key}=supabaseConfig(),token=await serverToken();const path=`${user.id}/profile.${ext}`;const response=await fetch(`${url}/storage/v1/object/avatars/${path}`,{method:'POST',headers:{apikey:key,Authorization:`Bearer ${token}`,'Content-Type':avatar.type,'x-upsert':'true'},body:avatar,cache:'no-store'});if(!response.ok)throw new Error('تعذر رفع صورة الحساب.');values.avatar_url=path;}await supabaseFetch(`/rest/v1/profiles?id=eq.${user.id}`,{method:'PATCH',body:JSON.stringify(values)});revalidatePath('/account');revalidatePath('/account/profile');revalidatePath('/');return {success:'تم حفظ الملف الشخصي وصورة الحساب.'};}catch(error){return {error:error instanceof Error?error.message:'تعذر حفظ الملف الشخصي.'};}}
