'use server';
import{revalidatePath}from'next/cache';import{requireUser}from'@/src/lib/auth';import{supabaseFetch,serverToken}from'@/src/lib/supabase/server';import{supabaseConfig}from'@/src/lib/env';import{required}from'@/src/lib/validation';import{validateMagicBytes}from'@/src/lib/file-signatures.mjs';
export type StudentState={success?:string;error?:string};
async function studentOrg(id:string){const user=await requireUser();const rows=await supabaseFetch(`/rest/v1/organization_members?organization_id=eq.${encodeURIComponent(id)}&user_id=eq.${user.id}&select=organization_id,organizations(type,status)`);if(rows?.[0]?.organizations?.type!=='STUDENT'||rows[0].organizations.status!=='active')throw new Error('هذه الأدوات مخصصة لمساحة الطالب.');return id;}
const result=async(work:()=>Promise<void>,success:string):Promise<StudentState>=>{try{await work();revalidatePath('/student');return{success}}catch(error){return{error:error instanceof Error?error.message:'تعذر حفظ البيانات.'}}};
export async function addCourse(_:StudentState,form:FormData){return result(async()=>{const organization_id=await studentOrg(required(form.get('organization_id'),'المساحة'));const credits=Number(form.get('credits')),grade=Number(form.get('grade'));if(!Number.isFinite(credits)||credits<=0||credits>30||!Number.isFinite(grade)||grade<0||grade>100)throw new Error('تحقق من الساعات والدرجة.');await supabaseFetch('/rest/v1/student_courses',{method:'POST',body:JSON.stringify({organization_id,name:required(form.get('name'),'المقرر'),credits,grade,semester:String(form.get('semester')||'').trim()||null})});},'تمت إضافة المقرر وحساب المعدل.')}
export async function addTask(_:StudentState,form:FormData){return result(async()=>{const organization_id=await studentOrg(required(form.get('organization_id'),'المساحة'));await supabaseFetch('/rest/v1/student_tasks',{method:'POST',body:JSON.stringify({organization_id,title:required(form.get('title'),'المهمة'),due_at:String(form.get('due_at')||'')||null})});},'تمت إضافة المهمة.')}
export async function toggleTask(form:FormData){const org=await studentOrg(required(form.get('organization_id'),'المساحة'));await supabaseFetch(`/rest/v1/student_tasks?id=eq.${encodeURIComponent(required(form.get('id'),'المهمة'))}&organization_id=eq.${org}`,{method:'PATCH',body:JSON.stringify({is_done:String(form.get('is_done'))!=='true'})});revalidatePath('/student')}
export async function addNote(_:StudentState,form:FormData){return result(async()=>{const organization_id=await studentOrg(required(form.get('organization_id'),'المساحة'));await supabaseFetch('/rest/v1/student_notes',{method:'POST',body:JSON.stringify({organization_id,title:required(form.get('title'),'العنوان'),content:required(form.get('content'),'الملاحظة')})});},'تم حفظ الملاحظة.')}
export async function addSchedule(_:StudentState,form:FormData){return result(async()=>{const organization_id=await studentOrg(required(form.get('organization_id'),'المساحة'));await supabaseFetch('/rest/v1/student_schedule',{method:'POST',body:JSON.stringify({organization_id,title:required(form.get('title'),'العنوان'),weekday:Number(form.get('weekday')),starts_at:required(form.get('starts_at'),'وقت البداية'),ends_at:required(form.get('ends_at'),'وقت النهاية'),location:String(form.get('location')||'').trim()||null})});},'تمت إضافة الموعد.')}
export async function uploadStudentPdf(_:StudentState,form:FormData){return result(async()=>{const organization_id=await studentOrg(required(form.get('organization_id'),'المساحة')),file=form.get('file');if(!(file instanceof File)||!file.size)throw new Error('اختر ملف PDF.');if(file.type!=='application/pdf'||file.size>20*1024*1024||!await validateMagicBytes(file))throw new Error('يجب أن يكون الملف PDF صالحًا وبحجم لا يتجاوز 20MB.');const path=`${organization_id}/${crypto.randomUUID()}.pdf`,{url,key}=supabaseConfig(),token=await serverToken();const response=await fetch(`${url}/storage/v1/object/student-library/${path}`,{method:'POST',headers:{apikey:key,Authorization:`Bearer ${token}`,'Content-Type':'application/pdf'},body:file,cache:'no-store'});if(!response.ok)throw new Error('تعذر رفع المرجع.');try{await supabaseFetch('/rest/v1/student_documents',{method:'POST',body:JSON.stringify({organization_id,title:required(form.get('title'),'العنوان'),subject:String(form.get('subject')||'').trim()||null,storage_path:path,original_filename:file.name,file_size:file.size})});}catch(error){await fetch(`${url}/storage/v1/object/student-library/${path}`,{method:'DELETE',headers:{apikey:key,Authorization:`Bearer ${token}`}});throw error;}},'تم وضع المرجع على رفك الرقمي.')}
