import ActionFeedback from '@/components/business/ActionFeedback';
import {createBusinessSupplier} from '@/app/actions/business';
import {businessMoney,requireBusinessWorkspace} from '@/src/lib/business';
import {supabaseFetch} from '@/src/lib/supabase/server';

export const dynamic='force-dynamic';export const metadata={title:'الموردون | مَدار'};
export default async function SuppliersPage({searchParams}:{searchParams:Promise<{success?:string;error?:string}>}){
 const{workspace}=await requireBusinessWorkspace(),params=await searchParams;
 const suppliers=await supabaseFetch(`/rest/v1/business_suppliers?organization_id=eq.${encodeURIComponent(workspace.id)}&select=*&order=created_at.desc`);
 return <main className="mx-auto max-w-7xl p-5 py-10"><h2 className="text-4xl font-black">الموردون</h2><p className="mt-2 text-slate-300">حفظ الموردين والمبالغ المستحقة تمهيدًا لأوامر الشراء.</p><div className="mt-8 grid gap-8 lg:grid-cols-[380px_1fr]"><section><ActionFeedback {...params}/><form action={createBusinessSupplier} className="grid gap-3 rounded-3xl border border-white/10 bg-white/[.04] p-5"><h3 className="text-xl font-black">إضافة مورد</h3><input className="field rounded-xl p-3" name="name" required placeholder="اسم المورد"/><input className="field rounded-xl p-3" name="contact_name" placeholder="اسم مسؤول التواصل"/><div className="grid grid-cols-2 gap-3"><input className="field rounded-xl p-3" name="phone" placeholder="الهاتف"/><input className="field rounded-xl p-3" name="email" type="email" placeholder="البريد"/></div><input className="field rounded-xl p-3" name="address" placeholder="العنوان"/><input className="field rounded-xl p-3" name="balance_due" type="number" min="0" step="0.01" defaultValue="0" required placeholder="الرصيد المستحق"/><textarea className="field rounded-xl p-3" name="notes" rows={3} placeholder="ملاحظات"/><button className="rounded-xl bg-white p-3 font-black text-slate-950">حفظ المورد</button></form></section><section className="grid gap-4 md:grid-cols-2">{suppliers?.length?suppliers.map((s:{id:string;name:string;contact_name:string|null;phone:string|null;email:string|null;address:string|null;balance_due:number;is_active:boolean;notes:string|null})=><article key={s.id} className="rounded-3xl border border-white/10 bg-white/[.04] p-5"><div className="flex justify-between gap-4"><div><h3 className="text-xl font-black">{s.name}</h3><p className="mt-1 text-sm text-slate-400">{s.contact_name||'دون مسؤول محدد'}</p></div><strong className="text-amber-200">{businessMoney(s.balance_due,workspace.currency)}</strong></div><p className="mt-4 text-sm text-slate-300">{s.phone||'لا يوجد هاتف'}{s.email?` · ${s.email}`:''}</p>{s.address&&<p className="mt-2 text-sm text-slate-400">{s.address}</p>}{s.notes&&<p className="mt-3 border-t border-white/10 pt-3 text-sm text-slate-400">{s.notes}</p>}</article>):<p className="md:col-span-2 rounded-3xl border border-white/10 p-10 text-center text-slate-400">لا يوجد موردون بعد.</p>}</section></div></main>;
}
