/* eslint-disable @typescript-eslint/no-explicit-any */
import Link from 'next/link';
import {requireAdmin} from '@/src/lib/auth';
import {supabaseFetch} from '@/src/lib/supabase/server';
import {money} from '@/src/lib/order-status';
export const dynamic='force-dynamic';

export default async function AdminPage(){
 const profile=await requireAdmin();let stats:any={};
 try{const[products,services,users,applications,workspaceRequests,orders,feedback,renewals,privacy]=await Promise.all([supabaseFetch('/rest/v1/products?select=status'),supabaseFetch('/rest/v1/services?select=status'),supabaseFetch('/rest/v1/profiles?select=id'),supabaseFetch('/rest/v1/job_applications?select=id,status'),supabaseFetch('/rest/v1/workspace_requests?select=id,status'),supabaseFetch('/rest/v1/orders?select=id,status,payment_status,total'),supabaseFetch('/rest/v1/platform_feedback?select=id,status'),supabaseFetch('/rest/v1/subscription_renewal_requests?select=id,status'),supabaseFetch('/rest/v1/data_privacy_requests?select=id,status')]);stats={products,services,users,applications,workspaceRequests,orders,feedback,renewals,privacy}}catch{}
 const count=(rows:any[],status?:string)=>rows?.filter(item=>!status||item.status===status).length||0,review=stats.orders?.filter((item:any)=>item.payment_status==='under_review').length||0,revenue=stats.orders?.filter((item:any)=>item.payment_status==='approved').reduce((total:number,item:any)=>total+Number(item.total),0)||0;
 const links=[['orders','طلبات ومدفوعات المتجر'],['reports','تقارير المتجر'],['coupons','الكوبونات'],['products','منتجات متجر مَدار'],['services','خدمات مَدار'],['categories','التصنيفات'],['users','المستخدمون'],['applications','طلبات التوظيف'],['workspace-requests','طلبات فتح المساحات'],['local-payments','الدفع المحلي والاشتراكات'],['beta-operations','تشغيل Beta والدعم'],['system-health','صحة المنصة']];
 return <main className="mx-auto max-w-7xl p-6 py-10"><div className="flex flex-wrap items-end justify-between gap-5"><div><h1 className="text-4xl font-black">لوحة إدارة منصة مَدار</h1><p className="mt-2 text-slate-300">{profile.full_name} · {profile.role}</p></div>{profile.role==='SUPER_ADMIN'&&<Link href="/admin/founder" className="rounded-2xl bg-gradient-to-l from-violet-500 to-emerald-400 px-6 py-4 font-black text-slate-950">مركز قيادة المؤسس</Link>}</div><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['كل طلبات المتجر',stats.orders?.length||0],['دفعات تنتظر المراجعة',review],['الإيراد المعتمد',money(revenue)],['المنتجات المنشورة',count(stats.products,'published')],['المستخدمون',stats.users?.length||0],['مساحات تنتظر القبول',count(stats.workspaceRequests,'pending_review')],['بلاغات Beta مفتوحة',stats.feedback?.filter((item:any)=>!['resolved','closed'].includes(item.status)).length||0],['تجديدات معلقة',count(stats.renewals,'under_review')],['طلبات خصوصية مفتوحة',stats.privacy?.filter((item:any)=>['requested','processing'].includes(item.status)).length||0],['طلبات توظيف جديدة',count(stats.applications,'new')],['الخدمات المنشورة',count(stats.services,'published')],['حالة الإدارة','نشطة']].map(([name,value])=><div className="rounded-2xl border border-white/10 bg-white/[.03] p-5" key={String(name)}><b>{name}</b><p className="mt-2 text-3xl font-black">{String(value)}</p></div>)}</div><h2 className="mt-10 text-2xl font-black">كل أدوات التحكم</h2><nav className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{links.map(([path,label])=><Link className="rounded-2xl border border-white/10 bg-white p-5 font-black text-slate-900 transition hover:-translate-y-0.5" href={`/admin/${path}`} key={path}>{label}</Link>)}</nav>{profile.role==='SUPER_ADMIN'&&<section className="mt-10 rounded-3xl border border-violet-300/20 bg-violet-300/[.05] p-6"><h2 className="text-2xl font-black text-violet-100">صلاحيات خاصة بالحساب المؤسس</h2><p className="mt-3 leading-8 text-slate-300">إدارة رتب الحسابات وتعطيلها، إيقاف المساحات، تعديل الاشتراكات، تشغيل الصيانة، فتح وإغلاق التسجيل والمتجر وأوربي، إرسال إشعارات عامة، ومراجعة سجل كل القرارات.</p><Link href="/admin/founder" className="mt-5 inline-block rounded-xl bg-violet-300 px-5 py-3 font-black text-violet-950">فتح مركز المؤسس</Link></section>}</main>;
}
