import ActionFeedback from '@/components/business/ActionFeedback';
import {adjustBusinessInventory} from '@/app/actions/business';
import {requireBusinessWorkspace} from '@/src/lib/business';
import {supabaseFetch} from '@/src/lib/supabase/server';

export const dynamic='force-dynamic';export const metadata={title:'المخزون | مَدار'};
export default async function InventoryPage({searchParams}:{searchParams:Promise<{success?:string;error?:string}>}){
 const{workspace}=await requireBusinessWorkspace(),params=await searchParams,id=encodeURIComponent(workspace.id);
 const[products,movements]=await Promise.all([supabaseFetch(`/rest/v1/business_products?organization_id=eq.${id}&is_active=eq.true&select=id,name,sku,stock_quantity,low_stock_threshold&order=name`),supabaseFetch(`/rest/v1/inventory_movements?organization_id=eq.${id}&select=id,movement_type,quantity_delta,balance_after,note,created_at,business_products(name)&order=created_at.desc&limit=100`)]);
 return <main className="mx-auto max-w-7xl p-5 py-10"><h2 className="text-4xl font-black">إدارة المخزون</h2><p className="mt-2 text-slate-300">كل تعديل يسجل كحركة مستقلة بدل تغيير الأرقام بصمت.</p><div className="mt-8 grid gap-8 lg:grid-cols-[360px_1fr]"><section><ActionFeedback {...params}/><form action={adjustBusinessInventory} className="grid gap-3 rounded-3xl border border-white/10 bg-white/[.04] p-5"><h3 className="text-xl font-black">تعديل الكمية</h3><select name="product_id" required className="field rounded-xl p-3"><option value="">اختر المنتج</option>{products?.map((p:{id:string;name:string;stock_quantity:number})=><option key={p.id} value={p.id}>{p.name} — المتاح {p.stock_quantity}</option>)}</select><input className="field rounded-xl p-3" name="quantity_change" type="number" step="0.001" required placeholder="مثال: 10 للإضافة أو -2 للخصم"/><textarea className="field rounded-xl p-3" name="note" rows={3} placeholder="سبب التعديل"/><button className="rounded-xl bg-white p-3 font-black text-slate-950">تسجيل الحركة</button></form><div className="mt-5 space-y-2">{products?.filter((p:{stock_quantity:number;low_stock_threshold:number})=>Number(p.stock_quantity)<=Number(p.low_stock_threshold)).map((p:{id:string;name:string;stock_quantity:number})=><p key={p.id} className="rounded-xl border border-amber-300/20 bg-amber-300/10 p-3 text-sm text-amber-100">{p.name}: بقي {p.stock_quantity}</p>)}</div></section><section className="rounded-3xl border border-white/10 p-5"><h3 className="text-xl font-black">سجل الحركات</h3><div className="mt-4 space-y-3">{movements?.length?movements.map((m:{id:string;movement_type:string;quantity_delta:number;balance_after:number;note:string|null;created_at:string;business_products:{name:string}|null})=><article key={m.id} className="grid gap-2 rounded-2xl bg-white/[.04] p-4 sm:grid-cols-4 sm:items-center"><strong>{m.business_products?.name||'منتج محذوف'}</strong><span className={Number(m.quantity_delta)>0?'text-emerald-200':'text-amber-200'}>{Number(m.quantity_delta)>0?'+':''}{m.quantity_delta}</span><span className="text-sm text-slate-300">الرصيد: {m.balance_after}</span><span className="text-xs text-slate-400">{new Date(m.created_at).toLocaleString('ar-YE')}</span>{m.note&&<p className="sm:col-span-4 text-sm text-slate-400">{m.note}</p>}</article>):<p className="p-8 text-center text-slate-400">لا توجد حركات مخزون بعد.</p>}</div></section></div></main>;
}
