import ActionFeedback from '@/components/business/ActionFeedback';
import {createBusinessExpense} from '@/app/actions/business';
import {businessMoney,requireBusinessWorkspace} from '@/src/lib/business';
import {supabaseFetch} from '@/src/lib/supabase/server';

export const dynamic='force-dynamic';export const metadata={title:'المصروفات | مَدار'};
export default async function ExpensesPage({searchParams}:{searchParams:Promise<{success?:string;error?:string}>}){
 const{workspace}=await requireBusinessWorkspace(),params=await searchParams,id=encodeURIComponent(workspace.id);
 const[suppliers,expenses]=await Promise.all([supabaseFetch(`/rest/v1/business_suppliers?organization_id=eq.${id}&is_active=eq.true&select=id,name&order=name`),supabaseFetch(`/rest/v1/business_expenses?organization_id=eq.${id}&select=id,title,category,amount,currency,incurred_at,payment_status,notes,business_suppliers(name)&order=incurred_at.desc,created_at.desc&limit=200`)]);
 const total=(expenses||[]).reduce((sum:number,row:{amount:number|string})=>sum+Number(row.amount),0);
 return <main className="mx-auto max-w-7xl p-5 py-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-4xl font-black">المصروفات</h2><p className="mt-2 text-slate-300">تسجيل التكاليف شرط أساسي لحساب الربح الحقيقي لاحقًا.</p></div><div className="rounded-2xl border border-white/10 p-4"><p className="text-xs text-slate-400">الإجمالي المسجل</p><strong className="text-2xl text-[#70E4D4]">{businessMoney(total,workspace.currency)}</strong></div></div><div className="mt-8 grid gap-8 lg:grid-cols-[380px_1fr]"><section><ActionFeedback {...params}/><form action={createBusinessExpense} className="grid gap-3 rounded-3xl border border-white/10 bg-white/[.04] p-5"><h3 className="text-xl font-black">تسجيل مصروف</h3><input className="field rounded-xl p-3" name="title" required placeholder="اسم المصروف"/><div className="grid grid-cols-2 gap-3"><input className="field rounded-xl p-3" name="category" placeholder="التصنيف"/><input className="field rounded-xl p-3" name="amount" type="number" min="0.01" step="0.01" required placeholder="المبلغ"/></div><input className="field rounded-xl p-3" name="incurred_at" type="date" required defaultValue={new Date().toISOString().slice(0,10)}/><select className="field rounded-xl p-3" name="supplier_id"><option value="">دون مورد</option>{suppliers?.map((s:{id:string;name:string})=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select className="field rounded-xl p-3" name="payment_status" defaultValue="paid"><option value="paid">مدفوع</option><option value="partial">مدفوع جزئيًا</option><option value="unpaid">غير مدفوع</option></select><textarea className="field rounded-xl p-3" name="notes" rows={3} placeholder="ملاحظات"/><button className="rounded-xl bg-gradient-to-l from-violet-500 to-emerald-400 p-3 font-black">حفظ المصروف</button></form></section><section className="space-y-3">{expenses?.length?expenses.map((expense:{id:string;title:string;category:string;amount:number;currency:string;incurred_at:string;payment_status:string;notes:string|null;business_suppliers:{name:string}|null})=><article key={expense.id} className="rounded-2xl border border-white/10 bg-white/[.04] p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><h3 className="font-black">{expense.title}</h3><p className="mt-1 text-sm text-slate-400">{expense.category} · {expense.business_suppliers?.name||'دون مورد'} · {expense.incurred_at}</p></div><div className="text-left"><strong className="text-xl">{businessMoney(expense.amount,expense.currency)}</strong><p className="text-xs text-slate-400">{expense.payment_status}</p></div></div>{expense.notes&&<p className="mt-3 border-t border-white/10 pt-3 text-sm text-slate-400">{expense.notes}</p>}</article>):<p className="rounded-3xl border border-white/10 p-10 text-center text-slate-400">لا توجد مصروفات بعد.</p>}</section></div></main>;
}
