import Link from 'next/link';
import ActionFeedback from '@/components/business/ActionFeedback';
import {reviewPrivacyRequest,updateBetaFeedback} from '@/app/actions/beta-operations';
import {requireAdmin} from '@/src/lib/auth';
import {supabaseFetch} from '@/src/lib/supabase/server';

export const dynamic='force-dynamic';export const metadata={title:'تشغيل Beta | مَدار'};
type Feedback={id:string;user_id:string;organization_id:string|null;feedback_type:string;severity:string;title:string;message:string;page_path:string|null;rating:number|null;status:string;admin_note:string|null;attachment_path:string|null;attachment_name:string|null;created_at:string};
type Privacy={id:string;user_id:string;organization_id:string|null;request_type:string;status:string;reason:string|null;admin_note:string|null;requested_at:string};
type Profile={id:string;full_name:string|null;email:string|null};type Organization={id:string;name:string};
const feedbackLabels:Record<string,string>={bug:'مشكلة',suggestion:'اقتراح',question:'سؤال',rating:'تقييم'},privacyLabels:Record<string,string>={export_account:'تصدير حساب',export_workspace:'تصدير مساحة',delete_account:'حذف حساب',delete_workspace:'حذف مساحة'};

export default async function BetaOperationsPage({searchParams}:{searchParams:Promise<{success?:string;error?:string}>}){
 await requireAdmin();const params=await searchParams;
 const[feedback,privacy,profiles,organizations]:[Feedback[],Privacy[],Profile[],Organization[]]=await Promise.all([
  supabaseFetch('/rest/v1/platform_feedback?select=*&order=created_at.desc&limit=300'),
  supabaseFetch('/rest/v1/data_privacy_requests?select=*&order=requested_at.desc&limit=300'),
  supabaseFetch('/rest/v1/profiles?select=id,full_name,email'),
  supabaseFetch('/rest/v1/organizations?select=id,name')
 ]);
 const profileMap=new Map(profiles.map(profile=>[profile.id,profile])),organizationMap=new Map(organizations.map(organization=>[organization.id,organization.name]));
 const openFeedback=feedback.filter(item=>!['resolved','closed'].includes(item.status)).length,openPrivacy=privacy.filter(item=>['requested','processing'].includes(item.status)).length;
 return <main className="mx-auto max-w-7xl p-6 py-10"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="font-bold text-[#70E4D4]">MADAR Beta Operations</p><h1 className="mt-2 text-4xl font-black">التشغيل والدعم والخصوصية</h1><p className="mt-3 text-slate-400">مراجعة بلاغات المستخدمين وطلبات التصدير والحذف من مركز واحد.</p></div><Link href="/admin" className="rounded-xl border border-white/15 px-4 py-3 font-bold">العودة للإدارة</Link></div><div className="mt-6"><ActionFeedback {...params}/></div><section className="mt-7 grid gap-4 sm:grid-cols-3"><Metric label="كل البلاغات" value={feedback.length}/><Metric label="بلاغات مفتوحة" value={openFeedback}/><Metric label="طلبات خصوصية مفتوحة" value={openPrivacy}/></section><section className="mt-10"><h2 className="text-2xl font-black">بلاغات ومقترحات Beta</h2><div className="mt-5 space-y-5">{feedback.map(item=><FeedbackCard key={item.id} item={item} user={profileMap.get(item.user_id)} organizationName={item.organization_id?organizationMap.get(item.organization_id):undefined}/>)}{!feedback.length&&<Empty text="لا توجد بلاغات."/>}</div></section><section className="mt-12"><h2 className="text-2xl font-black">طلبات الخصوصية والبيانات</h2><div className="mt-5 space-y-4">{privacy.map(item=><PrivacyCard key={item.id} item={item} user={profileMap.get(item.user_id)} organizationName={item.organization_id?organizationMap.get(item.organization_id):undefined}/>)}{!privacy.length&&<Empty text="لا توجد طلبات خصوصية."/>}</div></section></main>;
}

function FeedbackCard({item,user,organizationName}:{item:Feedback;user?:Profile;organizationName?:string}){return <article className="rounded-3xl border border-white/10 bg-white/[.03] p-6"><div className="grid gap-6 xl:grid-cols-[1fr_480px]"><div><div className="flex flex-wrap gap-2 text-xs"><span className="rounded-full bg-violet-300/10 px-3 py-1">{feedbackLabels[item.feedback_type]||item.feedback_type}</span><span className="rounded-full bg-white/10 px-3 py-1">{item.severity}</span><span className="rounded-full bg-white/10 px-3 py-1">{item.status}</span></div><h3 className="mt-3 text-xl font-black">{item.title}</h3><p className="mt-2 text-sm text-slate-400">{user?.full_name||'مستخدم'} · {user?.email||item.user_id}{organizationName?` · ${organizationName}`:''}</p><p className="mt-4 whitespace-pre-wrap leading-7 text-slate-300">{item.message}</p><div className="mt-4 flex flex-wrap gap-4 text-xs text-slate-500">{item.page_path&&<span>{item.page_path}</span>}{item.rating&&<span>التقييم {item.rating}/5</span>}<span>{new Date(item.created_at).toLocaleString('ar-YE')}</span>{item.attachment_path&&<Link className="font-bold text-[#70E4D4]" href={`/admin/beta-operations/attachment/${item.id}`}>فتح المرفق: {item.attachment_name||'ملف'}</Link>}</div></div><form action={updateBetaFeedback} className="grid content-start gap-3 rounded-2xl border border-white/10 p-5"><input type="hidden" name="feedback_id" value={item.id}/><label className="grid gap-2 text-sm font-bold">الحالة<select name="status" defaultValue={item.status} className="field rounded-xl p-3"><option value="new">جديد</option><option value="reviewing">قيد المراجعة</option><option value="planned">مخطط له</option><option value="resolved">تم الحل</option><option value="closed">مغلق</option></select></label><label className="grid gap-2 text-sm font-bold">رد الإدارة<textarea name="admin_note" defaultValue={item.admin_note||''} rows={5} maxLength={3000} className="field rounded-xl p-3"/></label><button className="rounded-xl bg-white p-3 font-black text-slate-950">حفظ والرد</button></form></div></article>}
function PrivacyCard({item,user,organizationName}:{item:Privacy;user?:Profile;organizationName?:string}){const open=['requested','processing'].includes(item.status);return <article className="grid gap-5 rounded-3xl border border-white/10 p-6 lg:grid-cols-[1fr_460px]"><div><div className="flex flex-wrap gap-2 text-xs"><span className="rounded-full bg-red-300/10 px-3 py-1 text-red-100">{privacyLabels[item.request_type]||item.request_type}</span><span className="rounded-full bg-white/10 px-3 py-1">{item.status}</span></div><h3 className="mt-3 font-black">{user?.full_name||'مستخدم'} · {user?.email||item.user_id}</h3>{organizationName&&<p className="mt-1 text-sm text-slate-400">المساحة: {organizationName}</p>}{item.reason&&<p className="mt-4 leading-7 text-slate-300">{item.reason}</p>}<p className="mt-3 text-xs text-slate-500">{new Date(item.requested_at).toLocaleString('ar-YE')}</p></div>{open?<form action={reviewPrivacyRequest} className="grid gap-3 rounded-2xl border border-white/10 p-5"><input type="hidden" name="request_id" value={item.id}/><label className="grid gap-2 text-sm font-bold">القرار<select name="status" defaultValue={item.status==='processing'?'processing':'processing'} className="field rounded-xl p-3"><option value="processing">بدء المعالجة</option><option value="completed">مكتمل</option><option value="rejected">رفض</option></select></label><label className="grid gap-2 text-sm font-bold">ملاحظة الإدارة<textarea name="admin_note" defaultValue={item.admin_note||''} rows={4} maxLength={3000} className="field rounded-xl p-3"/></label><button className="rounded-xl bg-[#00C292] p-3 font-black text-slate-950">حفظ القرار</button></form>:<div className="rounded-2xl border border-white/10 p-5"><p className="font-bold">الحالة النهائية: {item.status}</p>{item.admin_note&&<p className="mt-3 text-sm leading-7 text-slate-400">{item.admin_note}</p>}</div>}</article>}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded-2xl border border-white/10 bg-white/[.04] p-5"><p className="text-sm text-slate-400">{label}</p><strong className="mt-3 block text-3xl">{value.toLocaleString('ar-YE')}</strong></div>}
function Empty({text}:{text:string}){return <p className="rounded-3xl border border-dashed border-white/10 p-10 text-center text-slate-500">{text}</p>}
