import Image from 'next/image';
import Link from 'next/link';
import {siteConfig} from '@/src/config/site';
import {Icon,type IconName} from '@/components/ui/Icons';

const groups=[
 {title:'المنصة',links:[['الرئيسية','/'],['عن مَدار','/about'],['أوربي','/about#orby'],['المتجر','/store'],['المدونة','/blog']]},
 {title:'الموارد',links:[['الوثائق','/docs'],['مركز المساعدة','/help'],['الأسئلة الشائعة','/faq'],['المجتمع','/community'],['تواصل معنا','/contact']]},
 {title:'الشروط والسياسات',links:[['سياسة الخصوصية','/privacy'],['شروط الاستخدام','/terms'],['سياسة الاسترجاع','/refund-policy'],['اتفاقية الخدمة','/service-agreement']]},
];
const socials:{name:string;href:string;icon:IconName}[]=[{name:'حساب مَدار على منصة إكس',href:siteConfig.social.x,icon:'x'},{name:'حساب مَدار للصور والمقاطع',href:siteConfig.social.instagram,icon:'instagram'},{name:'التواصل المباشر مع مَدار',href:siteConfig.social.whatsapp,icon:'whatsapp'}];

export default function Footer(){return <footer className="border-t border-white/10 bg-[#060911] text-white md-no-print"><div className="md-container py-14 sm:py-18"><div className="grid gap-10 lg:grid-cols-[1.35fr_repeat(3,1fr)]"><div><Link href="/" className="inline-flex items-center gap-3 rounded-xl"><Image src={siteConfig.assets.logoWhite} alt="شعار مَدار" width={118} height={40} className="h-10 w-auto brightness-0 invert"/><span className="text-xl font-black">مَدار</span></Link><p className="mt-5 max-w-sm text-sm leading-7 text-slate-400">{siteConfig.description}</p><Link href={siteConfig.links.orby} className="mt-5 inline-flex"><span className="md-orby-chip"><Image src={siteConfig.assets.orby} alt="صورة أوربي" width={32} height={32} unoptimized className="md-orby-avatar"/><span>تعرّف على أوربي</span></span></Link><div className="mt-6 flex gap-2" aria-label="شبكات مَدار الاجتماعية">{socials.map(s=><a key={s.name} href={s.href} target="_blank" rel="noopener noreferrer" aria-label={s.name} title={s.name} className="grid h-11 w-11 place-items-center rounded-xl border border-white/10 bg-white/[.035] text-slate-400 transition hover:-translate-y-0.5 hover:border-emerald-300/30 hover:bg-emerald-300/10 hover:text-emerald-200"><Icon name={s.icon}/></a>)}</div></div>{groups.map(group=><div key={group.title}><h2 className="font-black text-white">{group.title}</h2><ul className="mt-5 space-y-3">{group.links.map(([label,href])=><li key={href}><Link href={href} className="text-sm text-slate-400 transition hover:text-white">{label}</Link></li>)}</ul></div>)}</div><div className="mt-12 flex flex-col gap-4 border-t border-white/10 pt-7 text-sm text-slate-500 sm:flex-row sm:items-center sm:justify-between"><p>© {new Date().getFullYear()} مَدار. {siteConfig.copyright}</p><a href={`mailto:${siteConfig.email}`} className="font-bold text-slate-400 transition hover:text-white">راسل فريق مَدار</a></div></div></footer>}
