import ActionFeedback from '@/components/business/ActionFeedback';
import {recordBusinessSale} from '@/app/actions/business';
import {businessMoney,requireBusinessWorkspace} from '@/src/lib/business';
import {supabaseFetch} from '@/src/lib/supabase/server';

export const dynamic='force-dynamic';export const metadata={title:'المبيعات | مَدار'};
export default async function SalesPage({searchParams}:{searchParams:Promise<{success?:string;error?:string}>}){
 const{workspace}=await requireBusinessWorkspace(),params=await searchParams,id=encodeURIComponent(workspace.id);
 const[products,customers,sales]=await Promise.all([supabaseFetch(`/rest/v1/business_products?organization_id=eq.${id}&is_active=eq.true&stock_quantity=gt.0&select=id,name,price,stock_quantity&order=name`),supabaseFetch(`/rest/v1/business_customers?organization_id=eq.${id}&status=neq.inactive&select=id,name,phone&order=name`),supabaseFetch(`/rest/v1/business_sales?organization_id=eq.${id}&select=id,sale_number,status,payment_status,total,currency,sold_at,business_customers(name)&order=sold_at.desc&limit=100`)]);
 return <main className="mx-auto max-w-7xl p-5 py-10"><h2 className="text-4xl font-black">المبيعات</h2><p className="mt-2 text-slate-300">تسجيل البيع يخفض المخزون ويحدّث إنفاق العميل في معاملة واحدة.</p><div className="mt-8 grid gap-8 lg:grid-cols-[380px_1fr]"><section><ActionFeedback {...params}/><form action={recordBusinessSale} className="grid gap-3 rounded-3xl border border-white/10 bg-white/[.04] p-5"><h3 className="text-xl font-black">عملية بيع جديدة</h3><select className="field rounded-xl p-3" name="product_id" required><option value="">اختر المنتج</option>{products?.map((p:{id:string;name:string;price:number;stock_quantity:number})=><option key={p.id} value={p.id}>{p.name} — {businessMoney(p.price,workspace.currency)} — متاح {p.stock_quantity}</option>)}</select><input className="field rounded-xl p-3" name="quantity" type="number" min="0.001" step="0.001" defaultValue="1" required/><select className="field rounded-xl p-3" name="customer_id"><option value="">بيع نقدي دون عميل</option>{customers?.map((c:{id:string;name:string;phone:string|null})=><option key={c.id} value={c.id}>{c.name}{c.phone?` — ${c.phone}`:''}</option>)}</select><div className="grid grid-cols-2 gap-3"><input className="field rounded-xl p-3" name="discount" type="number" min="0" step="0.01" defaultValue="0" required/><select className="field rounded-xl p-3" name="payment_status" defaultValue="paid"><option value="paid">مدفوع</option><option value="partial">مدفوع جزئيًا</option><option value="unpaid">غير مدفوع</option></select></div><textarea className="field rounded-xl p-3" name="notes" rows={3} placeholder="ملاحظات البيع"/><button className="rounded-xl bg-white p-3 font-black text-slate-950">تسجيل البيع</button></form></section><section className="rounded-3xl border border-white/10 p-5"><h3 className="text-xl font-black">آخر العمليات</h3><div className="mt-4 space-y-3">{sales?.length?sales.map((sale:{id:string;sale_number:string;status:string;payment_status:string;total:number;currency:string;sold_at:string;business_customers:{name:string}|null})=><article key={sale.id} className="grid gap-2 rounded-2xl bg-white/[.04] p-4 sm:grid-cols-4 sm:items-center"><div><strong dir="ltr">{sale.sale_number}</strong><p className="text-xs text-slate-400">{sale.business_customers?.name||'عميل نقدي'}</p></div><span>{sale.payment_status}</span><strong className="text-[#70E4D4]">{businessMoney(sale.total,sale.currency)}</strong><span className="text-xs text-slate-400">{new Date(sale.sold_at).toLocaleString('ar-YE')}</span></article>):<p className="p-8 text-center text-slate-400">لا توجد مبيعات بعد.</p>}</div></section></div></main>;
}
