import Link from 'next/link';
import {requireSuperAdmin} from '@/src/lib/auth';
import {supabaseFetch} from '@/src/lib/supabase/server';

export const dynamic='force-dynamic';export const metadata={title:'سجل قرارات المؤسس | مَدار'};
type AuditRow={id:string;actor_id:string|null;action:string;entity_type:string;entity_id:string|null;metadata:Record<string,unknown>;created_at:string};
type ProfileRow={id:string;full_name:string|null;email:string|null};
const actionLabels:Record<string,string>={'founder.user.updated':'تحديث حساب وصلاحية','founder.organization.updated':'تحديث مساحة عمل','founder.subscription.adjusted':'تعديل اشتراك','founder.notification.broadcast':'إرسال إشعار عام','platform.settings.updated':'تحديث إعدادات المنصة','privacy.request.created':'إنشاء طلب خصوصية','privacy.request.reviewed':'مراجعة طلب خصوصية','subscription.renewal.approved':'اعتماد تجديد اشتراك','orby.action.confirmed':'تنفيذ إجراء أوربي'};

export default async function FounderAuditPage({searchParams}:{searchParams:Promise<{action?:string}>}){
 await requireSuperAdmin();const params=await searchParams,filter=String(params.action||'').trim(),suffix=filter?`&action=eq.${encodeURIComponent(filter)}`:'';
 const logs:AuditRow[]=await supabaseFetch(`/rest/v1/audit_logs?select=id,actor_id,action,entity_type,entity_id,metadata,created_at&order=created_at.desc&limit=500${suffix}`),actorIds=[...new Set(logs.map(log=>log.actor_id).filter((id):id is string=>Boolean(id)))];
 const profiles:ProfileRow[]=actorIds.length?await supabaseFetch(`/rest/v1/profiles?id=in.(${actorIds.join(',')})&select=id,full_name,email`):[],actors=new Map(profiles.map(profile=>[profile.id,profile]));
 const actions=[...new Set(logs.map(log=>log.action))].sort();
 return <main className="mx-auto max-w-7xl p-6 py-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="font-bold text-violet-200">مركز المؤسس</p><h1 className="mt-2 text-4xl font-black">سجل القرارات والتدقيق</h1><p className="mt-3 text-slate-400">سجل زمني للعمليات الإدارية الحساسة. لا يُعرض إلا للحساب المؤسس.</p></div><Link href="/admin/founder" className="rounded-xl border border-white/15 px-4 py-3 font-bold">العودة لمركز القيادة</Link></div><form className="mt-7 flex flex-wrap items-end gap-3 rounded-2xl border border-white/10 p-4"><label className="grid min-w-[280px] gap-2 text-sm font-bold">نوع العملية<select name="action" defaultValue={filter} className="field rounded-xl p-3"><option value="">كل العمليات</option>{actions.map(action=><option key={action} value={action}>{actionLabels[action]||action}</option>)}</select></label><button className="rounded-xl bg-white px-5 py-3 font-black text-slate-950">تصفية</button></form><div className="mt-7 overflow-x-auto rounded-3xl border border-white/10"><table className="w-full min-w-[980px] text-right text-sm"><thead className="bg-white/[.05] text-slate-300"><tr><th className="p-4">الوقت</th><th className="p-4">المنفذ</th><th className="p-4">العملية</th><th className="p-4">الكيان</th><th className="p-4">التفاصيل</th></tr></thead><tbody>{logs.map(log=>{const actor=log.actor_id?actors.get(log.actor_id):null;return <tr key={log.id} className="border-t border-white/10 align-top"><td className="whitespace-nowrap p-4 text-slate-400">{new Date(log.created_at).toLocaleString('ar-YE')}</td><td className="p-4"><strong>{actor?.full_name||'النظام'}</strong><p className="mt-1 text-xs text-slate-500">{actor?.email||log.actor_id||'—'}</p></td><td className="p-4"><strong>{actionLabels[log.action]||log.action}</strong><p className="mt-1 text-xs text-slate-500">{log.action}</p></td><td className="p-4">{log.entity_type}<p className="mt-1 text-xs text-slate-500">{log.entity_id||'—'}</p></td><td className="max-w-xl p-4"><pre className="whitespace-pre-wrap break-words rounded-xl bg-black/20 p-3 text-xs leading-6 text-slate-300">{JSON.stringify(log.metadata,null,2)}</pre></td></tr>})}{!logs.length&&<tr><td colSpan={5} className="p-10 text-center text-slate-500">لا توجد عمليات مطابقة.</td></tr>}</tbody></table></div></main>;
}
