import Link from 'next/link';
import {requireBusinessWorkspace} from '@/src/lib/business';
import {supabaseFetch} from '@/src/lib/supabase/server';

export const dynamic='force-dynamic';export const metadata={title:'سجل نشاط المساحة | مَدار'};
type Activity={id:string;actor_id:string|null;action:string;entity_type:string;entity_id:string|null;metadata:Record<string,unknown>;created_at:string};
type Profile={id:string;full_name:string|null;email:string|null};
const actionLabels:Record<string,string>={'sale.created':'إنشاء عملية بيع','inventory.adjusted':'تعديل المخزون','business.product.created':'إضافة منتج','business.product.updated':'تحديث منتج','orby.action.confirmed':'تنفيذ إجراء أوربي','subscription.renewal.approved':'اعتماد تجديد الاشتراك','founder.organization.updated':'تحديث حالة المساحة','founder.subscription.adjusted':'تعديل الاشتراك','privacy.request.created':'طلب خصوصية جديد'};

export default async function WorkspaceActivityPage(){
 const{workspace}=await requireBusinessWorkspace(),activities:Activity[]=await supabaseFetch('/rest/v1/rpc/workspace_activity',{method:'POST',body:JSON.stringify({target_organization:workspace.id,result_limit:300})});
 const ids=[...new Set(activities.map(activity=>activity.actor_id).filter((id):id is string=>Boolean(id)))],profiles:Profile[]=ids.length?await supabaseFetch(`/rest/v1/profiles?id=in.(${ids.join(',')})&select=id,full_name,email`):[],actors=new Map(profiles.map(profile=>[profile.id,profile]));
 return <main className="mx-auto max-w-6xl p-6 py-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="font-bold text-[#70E4D4]">{workspace.name}</p><h2 className="mt-2 text-4xl font-black">سجل نشاط مساحة العمل</h2><p className="mt-3 text-slate-400">آخر العمليات الموثقة داخل هذه المساحة فقط، مرتبة من الأحدث.</p></div><Link href="/workspace" className="rounded-xl border border-white/15 px-4 py-3 font-bold">العودة إلى النظرة العامة</Link></div><section className="mt-8 space-y-4">{activities.map(activity=>{const actor=activity.actor_id?actors.get(activity.actor_id):null;return <article key={activity.id} className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex flex-wrap gap-2 text-xs"><span className="rounded-full bg-[#70E4D4]/10 px-3 py-1 text-[#baf7ee]">{actionLabels[activity.action]||activity.action}</span><span className="rounded-full bg-white/10 px-3 py-1">{activity.entity_type}</span></div><h3 className="mt-3 font-black">{actor?.full_name||'النظام أو الإدارة'}</h3><p className="mt-1 text-xs text-slate-500">{actor?.email||activity.actor_id||'عملية نظامية'}</p></div><time className="text-xs text-slate-500">{new Date(activity.created_at).toLocaleString('ar-YE')}</time></div><details className="mt-4"><summary className="cursor-pointer text-sm font-bold text-slate-400">تفاصيل العملية</summary><pre className="mt-3 whitespace-pre-wrap break-words rounded-xl bg-black/20 p-3 text-xs leading-6 text-slate-300">{JSON.stringify(activity.metadata,null,2)}</pre></details></article>})}{!activities.length&&<p className="rounded-3xl border border-dashed border-white/10 p-10 text-center text-slate-500">لا توجد عمليات موثقة حتى الآن.</p>}</section></main>;
}
