export const siteConfig = {
  name: 'مَدار | ORBIT',
  shortName: 'MADAR',
  companyName: 'MADAR Digital Systems',
  description:
    'منصة رقمية متخصصة في المنتجات الرقمية وأنظمة الذكاء الاصطناعي والأتمتة والقوالب الاحترافية لتطوير الأعمال.',
  baseUrl: 'https://madar.store',
  email: 'hello@madar.store',
  phone: '+966500000000',
  locale: 'ar_SA',
  themeColor: '#6C3BFF',
  copyright: 'جميع الحقوق محفوظة.',
  assets: {
    logo: '/logo.svg',
    logoWhite: '/logo-white.svg',
    favicon: '/logo.svg',
    appleTouchIcon: '/logo.svg',
    ogImage: '/logo.svg',
  },
  links: {
    home: '/',
    products: '#products',
    categories: '#categories',
    about: '#about',
    contact: '#contact',
    start: '#products',
    learnMore: '#about',
    privacy: '/privacy',
    terms: '/terms',
    refund: '/refund-policy',
    serviceAgreement: '/service-agreement',
    blog: '/blog',
    careers: '/careers',
    helpCenter: '/help',
    docs: '/docs',
    tutorials: '/tutorials',
    community: '/community',
  },
  social: {
    x: 'https://x.com/madar_store',
    linkedin: 'https://www.linkedin.com/company/madar-store',
    instagram: 'https://www.instagram.com/madar.store',
    youtube: 'https://www.youtube.com/@madarstore',
  },
  nav: [
    { label: 'المنتجات', href: '#products' },
    { label: 'الفئات', href: '#categories' },
    { label: 'عن مَدار', href: '#about' },
    { label: 'التواصل', href: '#contact' },
  ],
  seo: {
    title: 'مَدار | ORBIT - منصة المنتجات الرقمية المتخصصة',
    titleTemplate: '%s | مَدار',
    keywords: [
      'منتجات رقمية',
      'ذكاء اصطناعي',
      'أتمتة الأعمال',
      'قوالب احترافية',
      'Notion',
      'Google Sheets',
    ],
    twitterHandle: '@madar_store',
  },
  openGraph: {
    type: 'website',
    imageWidth: 1200,
    imageHeight: 630,
    imageAlt: 'مَدار | ORBIT - منصة المنتجات الرقمية المتخصصة',
  },
} as const;

export type SiteConfig = typeof siteConfig;
