import ActionFeedback from '@/components/business/ActionFeedback';
import {createBusinessTask,updateBusinessTaskStatus} from '@/app/actions/business';
import {requireBusinessWorkspace} from '@/src/lib/business';
import {supabaseFetch} from '@/src/lib/supabase/server';

export const dynamic='force-dynamic';export const metadata={title:'مهام التجارة | مَدار'};
const priority:{[key:string]:string}={low:'منخفضة',medium:'متوسطة',high:'عالية',urgent:'عاجلة'},status:{[key:string]:string}={todo:'جديدة',in_progress:'قيد التنفيذ',done:'مكتملة',cancelled:'ملغاة'};
export default async function TasksPage({searchParams}:{searchParams:Promise<{success?:string;error?:string}>}){
 const{workspace}=await requireBusinessWorkspace(),params=await searchParams;
 const tasks=await supabaseFetch(`/rest/v1/business_tasks?organization_id=eq.${encodeURIComponent(workspace.id)}&select=*&order=due_at.asc.nullslast,created_at.desc`);
 return <main className="mx-auto max-w-7xl p-5 py-10"><h2 className="text-4xl font-black">المهام التشغيلية</h2><p className="mt-2 text-slate-300">اجمع الأعمال اليومية والمواعيد في مساحة التجارة نفسها.</p><div className="mt-8 grid gap-8 lg:grid-cols-[380px_1fr]"><section><ActionFeedback {...params}/><form action={createBusinessTask} className="grid gap-3 rounded-3xl border border-white/10 bg-white/[.04] p-5"><h3 className="text-xl font-black">إضافة مهمة</h3><input className="field rounded-xl p-3" name="title" required placeholder="عنوان المهمة"/><textarea className="field rounded-xl p-3" name="description" rows={4} placeholder="التفاصيل"/><select className="field rounded-xl p-3" name="priority" defaultValue="medium"><option value="low">منخفضة</option><option value="medium">متوسطة</option><option value="high">عالية</option><option value="urgent">عاجلة</option></select><input className="field rounded-xl p-3" name="due_at" type="datetime-local"/><button className="rounded-xl bg-gradient-to-l from-violet-500 to-emerald-400 p-3 font-black">إضافة المهمة</button></form></section><section className="space-y-4">{tasks?.length?tasks.map((task:{id:string;title:string;description:string|null;priority:string;status:string;due_at:string|null})=><article key={task.id} className="rounded-3xl border border-white/10 bg-white/[.04] p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex flex-wrap gap-2 text-xs"><span className="rounded-full bg-violet-400/10 px-3 py-1 text-violet-100">{priority[task.priority]||task.priority}</span><span className="rounded-full bg-white/10 px-3 py-1">{status[task.status]||task.status}</span></div><h3 className="mt-3 text-xl font-black">{task.title}</h3>{task.description&&<p className="mt-2 leading-7 text-slate-300">{task.description}</p>}{task.due_at&&<p className="mt-3 text-sm text-amber-100">الموعد: {new Date(task.due_at).toLocaleString('ar-YE')}</p>}</div><form action={updateBusinessTaskStatus} className="flex gap-2"><input type="hidden" name="id" value={task.id}/><select name="status" defaultValue={task.status} className="field rounded-xl p-2 text-sm"><option value="todo">جديدة</option><option value="in_progress">قيد التنفيذ</option><option value="done">مكتملة</option><option value="cancelled">ملغاة</option></select><button className="rounded-xl bg-white px-3 py-2 text-sm font-bold text-slate-950">حفظ</button></form></div></article>):<p className="rounded-3xl border border-white/10 p-10 text-center text-slate-400">لا توجد مهام بعد.</p>}</section></div></main>;
}
