'use client';
import Link from 'next/link';
import {useActionState} from 'react';
import {login,register,forgotPassword} from '@/app/actions/auth';
import {Button,Field,Input,Notice,Panel} from '@/components/ui/Enterprise';

type Kind='login'|'register'|'forgot';type State={error?:string;success?:string};const actionByKind={login,register,forgot:forgotPassword};
export function AuthForm({kind,next,notice}:{kind:Kind;next?:string;notice?:string}){
 const action=actionByKind[kind] as(previous:State,formData:FormData)=>Promise<State>,[state,formAction,pending]=useActionState(action,{});
 return <Panel className="mx-auto max-w-md"><form action={formAction} className="grid gap-4" noValidate>{notice&&<Notice title="اكتمل إنشاء الحساب" variant="success">{notice}</Notice>}{kind==='register'&&<AuthField name="full_name" label="الاسم الكامل" autoComplete="name"/>}<AuthField name="email" label="البريد الإلكتروني" type="email" autoComplete="email"/>{kind!=='forgot'&&<><AuthField name="password" label="كلمة المرور" type="password" autoComplete={kind==='login'?'current-password':'new-password'}/>{kind==='register'&&<><AuthField name="confirm" label="تأكيد كلمة المرور" type="password" autoComplete="new-password"/><label className="flex items-start gap-3 rounded-xl border border-white/10 bg-white/[.025] p-3 text-sm leading-6 text-slate-300"><input required name="terms" type="checkbox" className="mt-1 h-4 w-4 accent-violet-500"/><span>أوافق على <Link href="/terms" target="_blank" className="font-bold text-emerald-300 underline underline-offset-4">شروط الاستخدام</Link> و<Link href="/privacy" target="_blank" className="font-bold text-emerald-300 underline underline-offset-4">سياسة الخصوصية</Link>.</span></label></>}</>}<input type="hidden" name="next" value={next||''}/><Button disabled={pending} className="w-full" size="lg">{pending?'جارٍ الإرسال…':kind==='login'?'تسجيل الدخول':kind==='register'?'إنشاء الحساب':'إرسال رابط الاستعادة'}</Button>{state.error&&<Notice title="تعذر إكمال العملية" variant="danger">{state.error}</Notice>}{state.success&&<Notice title="تمت العملية بنجاح" variant="success">{state.success}</Notice>}{kind==='login'&&<div className="flex flex-wrap items-center justify-center gap-2 text-sm text-slate-400"><Link href="/forgot-password" className="rounded-lg px-2 py-1 hover:bg-white/5 hover:text-white">نسيت كلمة المرور؟</Link><span aria-hidden="true">•</span><Link href="/register" className="rounded-lg px-2 py-1 hover:bg-white/5 hover:text-white">إنشاء حساب جديد</Link></div>}</form></Panel>;
}
function AuthField({name,label,type='text',autoComplete}:{name:string;label:string;type?:string;autoComplete?:string}){return <Field label={label}><Input required name={name} type={type} autoComplete={autoComplete}/></Field>}
