import Link from 'next/link';
import {requireSuperAdmin} from '@/src/lib/auth';
import {supabaseFetch} from '@/src/lib/supabase/server';

export const dynamic='force-dynamic';export const metadata={title:'صحة المنصة | مَدار'};
type Overview={users:{total:number;active:number;admins:number};workspaces:{total:number;active:number;suspended:number};store:{products:number;services:number;orders:number;approved_revenue:number};operations:{pending_workspace_requests:number;pending_renewals:number;open_feedback:number;privacy_requests:number};generated_at:string};
const scalar=<T,>(value:unknown)=>Array.isArray(value)?value[0] as T:value as T;
export default async function SystemHealthPage(){
 await requireSuperAdmin();
 const[settings,overview,methods,plans]=await Promise.all([supabaseFetch('/rest/v1/platform_settings?id=eq.1&select=*'),supabaseFetch('/rest/v1/rpc/founder_platform_overview',{method:'POST',body:'{}'}),supabaseFetch('/rest/v1/payment_methods?select=id,is_active,account_identifier,currency'),supabaseFetch('/rest/v1/subscription_plans?select=id,is_active,organization_type')]),config=settings?.[0],stats=scalar<Overview>(overview);
 const checks=[['قاعدة البيانات',Boolean(config),'متصلة وتستجيب'],['التسجيل التجريبي',Boolean(config?.beta_registration_open),config?.beta_registration_open?'مفتوح':'مغلق بقرار المؤسس'],['فتح المساحات',Boolean(config?.workspace_creation_enabled),config?.workspace_creation_enabled?'متاح':'موقوف'],['متجر مَدار',Boolean(config?.store_enabled),config?.store_enabled?'يستقبل الطلبات':'موقوف'],['أوربي',Boolean(config?.orby_enabled),config?.orby_enabled?'مفعّل':'موقوف'],['وضع الصيانة',!config?.maintenance_mode,config?.maintenance_mode?'مفعّل':'غير مفعّل'],['خطط الاشتراك',plans?.some((plan:{is_active:boolean})=>plan.is_active),`${plans?.filter((plan:{is_active:boolean})=>plan.is_active).length||0} خطة نشطة`],['وسائل الدفع الجاهزة',methods?.some((method:{is_active:boolean;account_identifier:string|null})=>method.is_active&&method.account_identifier),`${methods?.filter((method:{is_active:boolean;account_identifier:string|null})=>method.is_active&&method.account_identifier).length||0} طريقة نشطة`]];
 return <main className="mx-auto max-w-6xl p-6 py-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="font-bold text-violet-200">مركز المؤسس</p><h1 className="mt-2 text-4xl font-black">صحة المنصة واستعداد Beta</h1><p className="mt-3 text-slate-400">فحص مباشر لإعدادات التشغيل وقاعدة البيانات وتراكم الأعمال قبل الإطلاق.</p></div><div className="flex gap-3"><a href="/api/health" target="_blank" className="rounded-xl border border-[#70E4D4]/30 px-4 py-3 font-bold text-[#70E4D4]">فتح API الصحة</a><Link href="/admin/founder" className="rounded-xl border border-white/15 px-4 py-3 font-bold">مركز القيادة</Link></div></div><section className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{checks.map(([label,healthy,detail])=><article key={String(label)} className={`rounded-2xl border p-5 ${healthy?'border-emerald-300/20 bg-emerald-300/[.05]':'border-amber-300/20 bg-amber-300/[.06]'}`}><div className="flex items-center justify-between"><strong>{label}</strong><span className={`h-3 w-3 rounded-full ${healthy?'bg-emerald-300':'bg-amber-300'}`}/></div><p className="mt-3 text-sm text-slate-400">{detail}</p></article>)}</section><section className="mt-10 rounded-3xl border border-white/10 p-6"><h2 className="text-2xl font-black">مؤشرات التشغيل التي تحتاج انتباهًا</h2><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric label="طلبات فتح معلقة" value={stats.operations.pending_workspace_requests}/><Metric label="تجديدات معلقة" value={stats.operations.pending_renewals}/><Metric label="بلاغات Beta مفتوحة" value={stats.operations.open_feedback}/><Metric label="طلبات خصوصية" value={stats.operations.privacy_requests}/></div><div className="mt-6 grid gap-4 sm:grid-cols-3"><Metric label="الحسابات النشطة" value={stats.users.active}/><Metric label="المساحات النشطة" value={stats.workspaces.active}/><Metric label="طلبات المتجر" value={stats.store.orders}/></div></section><section className="mt-8 rounded-3xl border border-violet-300/20 bg-violet-300/[.05] p-6"><h2 className="text-xl font-black text-violet-100">قرار الإطلاق</h2><p className="mt-3 leading-8 text-slate-300">يُعد البناء التقني جاهزًا عندما تنجح اختبارات GitHub وبناء Vercel، ويكون فحص قاعدة البيانات متصلًا، وتوجد وسيلة دفع واحدة صحيحة على الأقل. تعطل Gemini لا يوقف Beta لأن أوربي يمتلك تحليلًا محليًا احتياطيًا.</p></section><p className="mt-6 text-xs text-slate-500">تم توليد الفحص: {new Date(stats.generated_at).toLocaleString('ar-YE')}</p></main>;
}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded-2xl border border-white/10 bg-white/[.03] p-4"><p className="text-xs text-slate-500">{label}</p><strong className="mt-2 block text-3xl">{value.toLocaleString('ar-YE')}</strong></div>}
