-- Use the internal authorization helper in RLS; the public wrapper is intentionally not executable.
drop policy "customers read own orders" on public.orders;
drop policy "admins update orders" on public.orders;
create policy "customers read own orders" on public.orders for select to authenticated using((select auth.uid())=user_id or private.is_admin());
create policy "admins update orders" on public.orders for update to authenticated using(private.is_admin()) with check(private.is_admin());
drop policy "customers read own items" on public.order_items;
create policy "customers read own items" on public.order_items for select to authenticated using(exists(select 1 from public.orders o where o.id=order_id and (o.user_id=(select auth.uid()) or private.is_admin())));
drop policy "customers read own proofs" on public.payment_proofs;
create policy "customers read own proofs" on public.payment_proofs for select to authenticated using(user_id=(select auth.uid()) or private.is_admin());
drop policy "customers read own history" on public.order_status_history;
create policy "customers read own history" on public.order_status_history for select to authenticated using(exists(select 1 from public.orders o where o.id=order_id and (o.user_id=(select auth.uid()) or private.is_admin())));
drop policy "admins manage coupons" on public.coupons;
create policy "admins manage coupons" on public.coupons for all to authenticated using(private.is_admin()) with check(private.is_admin());
drop policy "customers read own redemptions" on public.coupon_redemptions;
create policy "customers read own redemptions" on public.coupon_redemptions for select to authenticated using(user_id=(select auth.uid()) or private.is_admin());
drop policy "users or admins read notifications" on public.notifications;
create policy "users or admins read notifications" on public.notifications for select to authenticated using(user_id=(select auth.uid()) or private.is_admin());
drop policy "users read own downloads" on public.digital_downloads;
create policy "users read own downloads" on public.digital_downloads for select to authenticated using(user_id=(select auth.uid()) or private.is_admin());
drop policy "payment proof owner read" on storage.objects;
create policy "payment proof owner read" on storage.objects for select to authenticated using(bucket_id='payment-proofs' and ((storage.foldername(name))[1]=(select auth.uid())::text or private.is_admin()));
drop policy "paid customers download products" on storage.objects;
create policy "paid customers download products" on storage.objects for select to authenticated using(bucket_id='digital-products' and (private.is_admin() or exists(select 1 from public.product_files pf join public.order_items oi on oi.product_id=pf.product_id join public.orders o on o.id=oi.order_id where pf.storage_path=name and pf.is_active and o.user_id=(select auth.uid()) and o.payment_status='approved')));
drop policy "admins or paid customers read files" on public.product_files;
create policy "admins or paid customers read files" on public.product_files for select to authenticated using(private.is_admin() or (is_active and exists(select 1 from public.order_items oi join public.orders o on o.id=oi.order_id where oi.product_id=product_id and o.user_id=(select auth.uid()) and o.payment_status='approved')));
drop policy "admins insert product files" on public.product_files;drop policy "admins update product files" on public.product_files;drop policy "admins delete product files" on public.product_files;
create policy "admins insert product files" on public.product_files for insert to authenticated with check(private.is_admin());
create policy "admins update product files" on public.product_files for update to authenticated using(private.is_admin()) with check(private.is_admin());
create policy "admins delete product files" on public.product_files for delete to authenticated using(private.is_admin());
drop policy "public reads active plans" on public.subscription_plans;
create policy "public reads active plans" on public.subscription_plans for select to anon,authenticated using(is_active or private.is_admin());
drop policy "admins insert plans" on public.subscription_plans;drop policy "admins update plans" on public.subscription_plans;drop policy "admins delete plans" on public.subscription_plans;
create policy "admins insert plans" on public.subscription_plans for insert to authenticated with check(private.is_admin());
create policy "admins update plans" on public.subscription_plans for update to authenticated using(private.is_admin()) with check(private.is_admin());
create policy "admins delete plans" on public.subscription_plans for delete to authenticated using(private.is_admin());
drop policy "members read subscriptions" on public.workspace_subscriptions;
create policy "members read subscriptions" on public.workspace_subscriptions for select to authenticated using(private.is_admin() or exists(select 1 from public.organization_members m where m.organization_id=organization_id and m.user_id=(select auth.uid())));
drop policy "admins insert subscriptions" on public.workspace_subscriptions;drop policy "admins update subscriptions" on public.workspace_subscriptions;drop policy "admins delete subscriptions" on public.workspace_subscriptions;
create policy "admins insert subscriptions" on public.workspace_subscriptions for insert to authenticated with check(private.is_admin());
create policy "admins update subscriptions" on public.workspace_subscriptions for update to authenticated using(private.is_admin()) with check(private.is_admin());
create policy "admins delete subscriptions" on public.workspace_subscriptions for delete to authenticated using(private.is_admin());
